// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sort_C_sort_C,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.280333,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2375,HLS_SYN_LUT=8469,HLS_VERSION=2021_1}" *)

module sort_C (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        lenEdgeListPtr,
        fifoEdgeListPtr_i_V_dout,
        fifoEdgeListPtr_i_V_empty_n,
        fifoEdgeListPtr_i_V_read,
        fifoMatrixCIdx_i_0_V_dout,
        fifoMatrixCIdx_i_0_V_empty_n,
        fifoMatrixCIdx_i_0_V_read,
        fifoMatrixCIdx_i_1_V_dout,
        fifoMatrixCIdx_i_1_V_empty_n,
        fifoMatrixCIdx_i_1_V_read,
        fifoMatrixCIdx_i_2_V_dout,
        fifoMatrixCIdx_i_2_V_empty_n,
        fifoMatrixCIdx_i_2_V_read,
        fifoMatrixCIdx_i_3_V_dout,
        fifoMatrixCIdx_i_3_V_empty_n,
        fifoMatrixCIdx_i_3_V_read,
        fifoMatrixCIdx_i_4_V_dout,
        fifoMatrixCIdx_i_4_V_empty_n,
        fifoMatrixCIdx_i_4_V_read,
        fifoMatrixCIdx_i_5_V_dout,
        fifoMatrixCIdx_i_5_V_empty_n,
        fifoMatrixCIdx_i_5_V_read,
        fifoMatrixCIdx_i_6_V_dout,
        fifoMatrixCIdx_i_6_V_empty_n,
        fifoMatrixCIdx_i_6_V_read,
        fifoMatrixCIdx_i_7_V_dout,
        fifoMatrixCIdx_i_7_V_empty_n,
        fifoMatrixCIdx_i_7_V_read,
        fifoCalcMatrixC_i_0_V_dout,
        fifoCalcMatrixC_i_0_V_empty_n,
        fifoCalcMatrixC_i_0_V_read,
        fifoCalcMatrixC_i_1_V_dout,
        fifoCalcMatrixC_i_1_V_empty_n,
        fifoCalcMatrixC_i_1_V_read,
        fifoCalcMatrixC_i_2_V_dout,
        fifoCalcMatrixC_i_2_V_empty_n,
        fifoCalcMatrixC_i_2_V_read,
        fifoCalcMatrixC_i_3_V_dout,
        fifoCalcMatrixC_i_3_V_empty_n,
        fifoCalcMatrixC_i_3_V_read,
        fifoCalcMatrixC_i_4_V_dout,
        fifoCalcMatrixC_i_4_V_empty_n,
        fifoCalcMatrixC_i_4_V_read,
        fifoCalcMatrixC_i_5_V_dout,
        fifoCalcMatrixC_i_5_V_empty_n,
        fifoCalcMatrixC_i_5_V_read,
        fifoCalcMatrixC_i_6_V_dout,
        fifoCalcMatrixC_i_6_V_empty_n,
        fifoCalcMatrixC_i_6_V_read,
        fifoCalcMatrixC_i_7_V_dout,
        fifoCalcMatrixC_i_7_V_empty_n,
        fifoCalcMatrixC_i_7_V_read,
        fifoSortMatrixC_o_0_V_din,
        fifoSortMatrixC_o_0_V_full_n,
        fifoSortMatrixC_o_0_V_write,
        fifoSortMatrixC_o_1_V_din,
        fifoSortMatrixC_o_1_V_full_n,
        fifoSortMatrixC_o_1_V_write,
        fifoSortMatrixC_o_2_V_din,
        fifoSortMatrixC_o_2_V_full_n,
        fifoSortMatrixC_o_2_V_write,
        fifoSortMatrixC_o_3_V_din,
        fifoSortMatrixC_o_3_V_full_n,
        fifoSortMatrixC_o_3_V_write,
        fifoSortMatrixC_o_4_V_din,
        fifoSortMatrixC_o_4_V_full_n,
        fifoSortMatrixC_o_4_V_write,
        fifoSortMatrixC_o_5_V_din,
        fifoSortMatrixC_o_5_V_full_n,
        fifoSortMatrixC_o_5_V_write,
        fifoSortMatrixC_o_6_V_din,
        fifoSortMatrixC_o_6_V_full_n,
        fifoSortMatrixC_o_6_V_write,
        fifoSortMatrixC_o_7_V_din,
        fifoSortMatrixC_o_7_V_full_n,
        fifoSortMatrixC_o_7_V_write
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] lenEdgeListPtr;
input  [31:0] fifoEdgeListPtr_i_V_dout;
input   fifoEdgeListPtr_i_V_empty_n;
output   fifoEdgeListPtr_i_V_read;
input  [15:0] fifoMatrixCIdx_i_0_V_dout;
input   fifoMatrixCIdx_i_0_V_empty_n;
output   fifoMatrixCIdx_i_0_V_read;
input  [15:0] fifoMatrixCIdx_i_1_V_dout;
input   fifoMatrixCIdx_i_1_V_empty_n;
output   fifoMatrixCIdx_i_1_V_read;
input  [15:0] fifoMatrixCIdx_i_2_V_dout;
input   fifoMatrixCIdx_i_2_V_empty_n;
output   fifoMatrixCIdx_i_2_V_read;
input  [15:0] fifoMatrixCIdx_i_3_V_dout;
input   fifoMatrixCIdx_i_3_V_empty_n;
output   fifoMatrixCIdx_i_3_V_read;
input  [15:0] fifoMatrixCIdx_i_4_V_dout;
input   fifoMatrixCIdx_i_4_V_empty_n;
output   fifoMatrixCIdx_i_4_V_read;
input  [15:0] fifoMatrixCIdx_i_5_V_dout;
input   fifoMatrixCIdx_i_5_V_empty_n;
output   fifoMatrixCIdx_i_5_V_read;
input  [15:0] fifoMatrixCIdx_i_6_V_dout;
input   fifoMatrixCIdx_i_6_V_empty_n;
output   fifoMatrixCIdx_i_6_V_read;
input  [15:0] fifoMatrixCIdx_i_7_V_dout;
input   fifoMatrixCIdx_i_7_V_empty_n;
output   fifoMatrixCIdx_i_7_V_read;
input  [31:0] fifoCalcMatrixC_i_0_V_dout;
input   fifoCalcMatrixC_i_0_V_empty_n;
output   fifoCalcMatrixC_i_0_V_read;
input  [31:0] fifoCalcMatrixC_i_1_V_dout;
input   fifoCalcMatrixC_i_1_V_empty_n;
output   fifoCalcMatrixC_i_1_V_read;
input  [31:0] fifoCalcMatrixC_i_2_V_dout;
input   fifoCalcMatrixC_i_2_V_empty_n;
output   fifoCalcMatrixC_i_2_V_read;
input  [31:0] fifoCalcMatrixC_i_3_V_dout;
input   fifoCalcMatrixC_i_3_V_empty_n;
output   fifoCalcMatrixC_i_3_V_read;
input  [31:0] fifoCalcMatrixC_i_4_V_dout;
input   fifoCalcMatrixC_i_4_V_empty_n;
output   fifoCalcMatrixC_i_4_V_read;
input  [31:0] fifoCalcMatrixC_i_5_V_dout;
input   fifoCalcMatrixC_i_5_V_empty_n;
output   fifoCalcMatrixC_i_5_V_read;
input  [31:0] fifoCalcMatrixC_i_6_V_dout;
input   fifoCalcMatrixC_i_6_V_empty_n;
output   fifoCalcMatrixC_i_6_V_read;
input  [31:0] fifoCalcMatrixC_i_7_V_dout;
input   fifoCalcMatrixC_i_7_V_empty_n;
output   fifoCalcMatrixC_i_7_V_read;
output  [31:0] fifoSortMatrixC_o_0_V_din;
input   fifoSortMatrixC_o_0_V_full_n;
output   fifoSortMatrixC_o_0_V_write;
output  [31:0] fifoSortMatrixC_o_1_V_din;
input   fifoSortMatrixC_o_1_V_full_n;
output   fifoSortMatrixC_o_1_V_write;
output  [31:0] fifoSortMatrixC_o_2_V_din;
input   fifoSortMatrixC_o_2_V_full_n;
output   fifoSortMatrixC_o_2_V_write;
output  [31:0] fifoSortMatrixC_o_3_V_din;
input   fifoSortMatrixC_o_3_V_full_n;
output   fifoSortMatrixC_o_3_V_write;
output  [31:0] fifoSortMatrixC_o_4_V_din;
input   fifoSortMatrixC_o_4_V_full_n;
output   fifoSortMatrixC_o_4_V_write;
output  [31:0] fifoSortMatrixC_o_5_V_din;
input   fifoSortMatrixC_o_5_V_full_n;
output   fifoSortMatrixC_o_5_V_write;
output  [31:0] fifoSortMatrixC_o_6_V_din;
input   fifoSortMatrixC_o_6_V_full_n;
output   fifoSortMatrixC_o_6_V_write;
output  [31:0] fifoSortMatrixC_o_7_V_din;
input   fifoSortMatrixC_o_7_V_full_n;
output   fifoSortMatrixC_o_7_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fifoEdgeListPtr_i_V_read;
reg fifoMatrixCIdx_i_0_V_read;
reg fifoMatrixCIdx_i_1_V_read;
reg fifoMatrixCIdx_i_2_V_read;
reg fifoMatrixCIdx_i_3_V_read;
reg fifoMatrixCIdx_i_4_V_read;
reg fifoMatrixCIdx_i_5_V_read;
reg fifoMatrixCIdx_i_6_V_read;
reg fifoMatrixCIdx_i_7_V_read;
reg fifoCalcMatrixC_i_0_V_read;
reg fifoCalcMatrixC_i_1_V_read;
reg fifoCalcMatrixC_i_2_V_read;
reg fifoCalcMatrixC_i_3_V_read;
reg fifoCalcMatrixC_i_4_V_read;
reg fifoCalcMatrixC_i_5_V_read;
reg fifoCalcMatrixC_i_6_V_read;
reg fifoCalcMatrixC_i_7_V_read;
reg fifoSortMatrixC_o_0_V_write;
reg fifoSortMatrixC_o_1_V_write;
reg fifoSortMatrixC_o_2_V_write;
reg fifoSortMatrixC_o_3_V_write;
reg fifoSortMatrixC_o_4_V_write;
reg fifoSortMatrixC_o_5_V_write;
reg fifoSortMatrixC_o_6_V_write;
reg fifoSortMatrixC_o_7_V_write;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    fifoEdgeListPtr_i_V_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln135_fu_540_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln143_fu_594_p2;
reg    fifoSortMatrixC_o_0_V_blk_n;
wire    ap_CS_fsm_state11;
reg   [3:0] j_1_reg_463;
reg    fifoSortMatrixC_o_1_V_blk_n;
reg    fifoSortMatrixC_o_2_V_blk_n;
reg    fifoSortMatrixC_o_3_V_blk_n;
reg    fifoSortMatrixC_o_4_V_blk_n;
reg    fifoSortMatrixC_o_5_V_blk_n;
reg    fifoSortMatrixC_o_6_V_blk_n;
reg    fifoSortMatrixC_o_7_V_blk_n;
wire   [3:0] add_ln135_fu_546_p2;
reg   [3:0] add_ln135_reg_1064;
reg   [2:0] matrixC_buffer_V_0_addr_reg_1069;
reg   [2:0] matrixC_buffer_V_1_addr_reg_1074;
reg   [2:0] matrixC_buffer_V_2_addr_reg_1079;
reg   [2:0] matrixC_buffer_V_3_addr_reg_1084;
reg   [2:0] matrixC_buffer_V_4_addr_reg_1089;
reg   [2:0] matrixC_buffer_V_5_addr_reg_1094;
reg   [2:0] matrixC_buffer_V_6_addr_reg_1099;
reg   [2:0] matrixC_buffer_V_7_addr_reg_1104;
wire   [31:0] add_ln143_fu_552_p2;
reg   [31:0] add_ln143_reg_1123;
wire   [3:0] add_ln136_fu_573_p2;
reg   [3:0] add_ln136_reg_1131;
wire    ap_CS_fsm_state3;
reg   [31:0] tmp_47_reg_1142;
wire   [33:0] tmp_s_fu_636_p3;
reg   [33:0] tmp_s_reg_1156;
wire    ap_CS_fsm_state6;
wire   [3:0] add_ln168_fu_670_p2;
reg   [3:0] add_ln168_reg_1164;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln168_fu_664_p2;
wire   [31:0] matrixC_buffer_V_0_q0;
reg   [31:0] matrixC_buffer_V_0_load_reg_1209;
wire    ap_CS_fsm_state9;
wire   [31:0] matrixC_buffer_V_1_q0;
reg   [31:0] matrixC_buffer_V_1_load_reg_1214;
wire   [31:0] matrixC_buffer_V_2_q0;
reg   [31:0] matrixC_buffer_V_2_load_reg_1219;
wire   [31:0] matrixC_buffer_V_3_q0;
reg   [31:0] matrixC_buffer_V_3_load_reg_1224;
wire   [31:0] matrixC_buffer_V_4_q0;
reg   [31:0] matrixC_buffer_V_4_load_reg_1229;
wire   [31:0] matrixC_buffer_V_5_q0;
reg   [31:0] matrixC_buffer_V_5_load_reg_1234;
wire   [31:0] matrixC_buffer_V_6_q0;
reg   [31:0] matrixC_buffer_V_6_load_reg_1239;
wire   [31:0] matrixC_buffer_V_7_q0;
reg   [31:0] matrixC_buffer_V_7_load_reg_1244;
wire   [3:0] add_ln169_fu_682_p2;
reg   [3:0] add_ln169_reg_1252;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln988_fu_706_p2;
reg   [0:0] icmp_ln988_reg_1257;
wire   [0:0] icmp_ln169_fu_676_p2;
wire   [0:0] p_Result_2_fu_712_p3;
reg   [0:0] p_Result_2_reg_1262;
reg   [62:0] m_4_reg_1267;
reg   [0:0] p_Result_s_reg_1272;
wire   [7:0] trunc_ln996_fu_946_p1;
reg   [7:0] trunc_ln996_reg_1277;
reg   [2:0] matrixC_buffer_V_0_address0;
reg    matrixC_buffer_V_0_ce0;
reg    matrixC_buffer_V_0_we0;
reg   [31:0] matrixC_buffer_V_0_d0;
reg   [2:0] matrixC_buffer_V_1_address0;
reg    matrixC_buffer_V_1_ce0;
reg    matrixC_buffer_V_1_we0;
reg   [31:0] matrixC_buffer_V_1_d0;
reg   [2:0] matrixC_buffer_V_2_address0;
reg    matrixC_buffer_V_2_ce0;
reg    matrixC_buffer_V_2_we0;
reg   [31:0] matrixC_buffer_V_2_d0;
reg   [2:0] matrixC_buffer_V_3_address0;
reg    matrixC_buffer_V_3_ce0;
reg    matrixC_buffer_V_3_we0;
reg   [31:0] matrixC_buffer_V_3_d0;
reg   [2:0] matrixC_buffer_V_4_address0;
reg    matrixC_buffer_V_4_ce0;
reg    matrixC_buffer_V_4_we0;
reg   [31:0] matrixC_buffer_V_4_d0;
reg   [2:0] matrixC_buffer_V_5_address0;
reg    matrixC_buffer_V_5_ce0;
reg    matrixC_buffer_V_5_we0;
reg   [31:0] matrixC_buffer_V_5_d0;
reg   [2:0] matrixC_buffer_V_6_address0;
reg    matrixC_buffer_V_6_ce0;
reg    matrixC_buffer_V_6_we0;
reg   [31:0] matrixC_buffer_V_6_d0;
reg   [2:0] matrixC_buffer_V_7_address0;
reg    matrixC_buffer_V_7_ce0;
reg    matrixC_buffer_V_7_we0;
reg   [31:0] matrixC_buffer_V_7_d0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_done;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_idle;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_ready;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_4_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_4_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_5_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_5_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_6_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_6_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_7_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_7_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_3_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_3_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_2_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_2_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_1_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_1_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_0_V_read;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_0_V_read;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_d0;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_d0;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_d0;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_d0;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_d0;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_d0;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_d0;
wire   [2:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_address0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_ce0;
wire    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_we0;
wire   [31:0] grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_d0;
reg   [3:0] j_reg_452;
wire    ap_CS_fsm_state4;
reg    ap_block_state2;
reg    ap_predicate_op261_write_state11;
reg    ap_block_state11;
reg    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln135_fu_528_p1;
wire   [63:0] zext_ln168_fu_652_p1;
reg   [3:0] i_fu_184;
wire   [0:0] icmp_ln136_fu_567_p2;
reg   [30:0] iter_fu_220;
wire   [30:0] iter_2_fu_599_p2;
reg    ap_block_state5;
reg   [31:0] i_1_fu_224;
reg   [3:0] i_2_fu_228;
wire   [2:0] trunc_ln137_fu_579_p1;
wire   [31:0] zext_ln143_fu_590_p1;
wire   [0:0] empty_24_fu_618_p2;
wire   [31:0] smax_fu_623_p3;
wire   [31:0] sub_ln148_fu_630_p2;
wire   [2:0] p_Val2_s_fu_692_p9;
wire   [31:0] p_Val2_s_fu_692_p10;
wire   [31:0] tmp_V_fu_720_p2;
wire   [31:0] tmp_V_2_fu_726_p3;
reg   [31:0] p_Result_3_fu_734_p4;
reg   [31:0] l_fu_744_p3;
wire   [31:0] sub_ln997_fu_752_p2;
wire   [31:0] lsb_index_fu_758_p2;
wire   [30:0] tmp_43_fu_764_p4;
wire   [5:0] trunc_ln1000_fu_780_p1;
wire   [5:0] sub_ln1000_fu_784_p2;
wire   [31:0] zext_ln1000_fu_790_p1;
wire   [31:0] lshr_ln1000_fu_794_p2;
wire   [31:0] shl_ln1002_fu_800_p2;
wire   [31:0] or_ln1002_1_fu_806_p2;
wire   [31:0] and_ln1002_fu_812_p2;
wire   [0:0] tmp_44_fu_828_p3;
wire   [0:0] icmp_ln999_fu_774_p2;
wire   [0:0] icmp_ln1002_fu_818_p2;
wire   [0:0] p_Result_4_fu_842_p3;
wire   [31:0] add_ln1011_fu_864_p2;
wire   [63:0] zext_ln1010_fu_824_p1;
wire   [63:0] zext_ln1011_fu_870_p1;
wire   [0:0] xor_ln1002_fu_836_p2;
wire   [31:0] sub_ln1012_fu_886_p2;
wire   [63:0] zext_ln1012_fu_892_p1;
wire   [0:0] icmp_ln1011_fu_850_p2;
wire   [0:0] select_ln999_fu_856_p3;
wire   [0:0] and_ln1002_1_fu_880_p2;
wire   [63:0] lshr_ln1011_fu_874_p2;
wire   [63:0] shl_ln1012_fu_896_p2;
wire   [0:0] select_ln1011_fu_902_p3;
wire   [63:0] m_2_fu_910_p3;
wire   [63:0] zext_ln1014_fu_918_p1;
wire   [63:0] m_3_fu_922_p2;
wire   [7:0] sub_ln1017_fu_964_p2;
wire   [7:0] select_ln996_fu_957_p3;
wire   [7:0] add_ln1017_fu_969_p2;
wire   [63:0] zext_ln1015_fu_954_p1;
wire   [8:0] tmp_fu_975_p3;
wire   [63:0] p_Result_5_fu_982_p5;
wire   [31:0] LD_fu_994_p1;
wire   [31:0] bitcast_ln751_fu_998_p1;
wire   [31:0] select_ln988_fu_1002_p3;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start_reg = 1'b0;
end

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_0_address0),
    .ce0(matrixC_buffer_V_0_ce0),
    .we0(matrixC_buffer_V_0_we0),
    .d0(matrixC_buffer_V_0_d0),
    .q0(matrixC_buffer_V_0_q0)
);

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_1_address0),
    .ce0(matrixC_buffer_V_1_ce0),
    .we0(matrixC_buffer_V_1_we0),
    .d0(matrixC_buffer_V_1_d0),
    .q0(matrixC_buffer_V_1_q0)
);

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_2_address0),
    .ce0(matrixC_buffer_V_2_ce0),
    .we0(matrixC_buffer_V_2_we0),
    .d0(matrixC_buffer_V_2_d0),
    .q0(matrixC_buffer_V_2_q0)
);

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_3_address0),
    .ce0(matrixC_buffer_V_3_ce0),
    .we0(matrixC_buffer_V_3_we0),
    .d0(matrixC_buffer_V_3_d0),
    .q0(matrixC_buffer_V_3_q0)
);

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_4_address0),
    .ce0(matrixC_buffer_V_4_ce0),
    .we0(matrixC_buffer_V_4_we0),
    .d0(matrixC_buffer_V_4_d0),
    .q0(matrixC_buffer_V_4_q0)
);

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_5_address0),
    .ce0(matrixC_buffer_V_5_ce0),
    .we0(matrixC_buffer_V_5_we0),
    .d0(matrixC_buffer_V_5_d0),
    .q0(matrixC_buffer_V_5_q0)
);

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_6_address0),
    .ce0(matrixC_buffer_V_6_ce0),
    .we0(matrixC_buffer_V_6_we0),
    .d0(matrixC_buffer_V_6_d0),
    .q0(matrixC_buffer_V_6_q0)
);

sort_C_matrixC_buffer_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
matrixC_buffer_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(matrixC_buffer_V_7_address0),
    .ce0(matrixC_buffer_V_7_ce0),
    .we0(matrixC_buffer_V_7_we0),
    .d0(matrixC_buffer_V_7_d0),
    .q0(matrixC_buffer_V_7_q0)
);

sort_C_sort_C_Pipeline_loop_diff_window_loop_diff_pe grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start),
    .ap_done(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_done),
    .ap_idle(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_idle),
    .ap_ready(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_ready),
    .fifoMatrixCIdx_i_4_V_dout(fifoMatrixCIdx_i_4_V_dout),
    .fifoMatrixCIdx_i_4_V_empty_n(fifoMatrixCIdx_i_4_V_empty_n),
    .fifoMatrixCIdx_i_4_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_4_V_read),
    .fifoCalcMatrixC_i_4_V_dout(fifoCalcMatrixC_i_4_V_dout),
    .fifoCalcMatrixC_i_4_V_empty_n(fifoCalcMatrixC_i_4_V_empty_n),
    .fifoCalcMatrixC_i_4_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_4_V_read),
    .fifoMatrixCIdx_i_5_V_dout(fifoMatrixCIdx_i_5_V_dout),
    .fifoMatrixCIdx_i_5_V_empty_n(fifoMatrixCIdx_i_5_V_empty_n),
    .fifoMatrixCIdx_i_5_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_5_V_read),
    .fifoCalcMatrixC_i_5_V_dout(fifoCalcMatrixC_i_5_V_dout),
    .fifoCalcMatrixC_i_5_V_empty_n(fifoCalcMatrixC_i_5_V_empty_n),
    .fifoCalcMatrixC_i_5_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_5_V_read),
    .fifoMatrixCIdx_i_6_V_dout(fifoMatrixCIdx_i_6_V_dout),
    .fifoMatrixCIdx_i_6_V_empty_n(fifoMatrixCIdx_i_6_V_empty_n),
    .fifoMatrixCIdx_i_6_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_6_V_read),
    .fifoCalcMatrixC_i_6_V_dout(fifoCalcMatrixC_i_6_V_dout),
    .fifoCalcMatrixC_i_6_V_empty_n(fifoCalcMatrixC_i_6_V_empty_n),
    .fifoCalcMatrixC_i_6_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_6_V_read),
    .fifoMatrixCIdx_i_7_V_dout(fifoMatrixCIdx_i_7_V_dout),
    .fifoMatrixCIdx_i_7_V_empty_n(fifoMatrixCIdx_i_7_V_empty_n),
    .fifoMatrixCIdx_i_7_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_7_V_read),
    .fifoCalcMatrixC_i_7_V_dout(fifoCalcMatrixC_i_7_V_dout),
    .fifoCalcMatrixC_i_7_V_empty_n(fifoCalcMatrixC_i_7_V_empty_n),
    .fifoCalcMatrixC_i_7_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_7_V_read),
    .zext_ln143_1(tmp_s_reg_1156),
    .fifoMatrixCIdx_i_3_V_dout(fifoMatrixCIdx_i_3_V_dout),
    .fifoMatrixCIdx_i_3_V_empty_n(fifoMatrixCIdx_i_3_V_empty_n),
    .fifoMatrixCIdx_i_3_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_3_V_read),
    .fifoCalcMatrixC_i_3_V_dout(fifoCalcMatrixC_i_3_V_dout),
    .fifoCalcMatrixC_i_3_V_empty_n(fifoCalcMatrixC_i_3_V_empty_n),
    .fifoCalcMatrixC_i_3_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_3_V_read),
    .fifoMatrixCIdx_i_2_V_dout(fifoMatrixCIdx_i_2_V_dout),
    .fifoMatrixCIdx_i_2_V_empty_n(fifoMatrixCIdx_i_2_V_empty_n),
    .fifoMatrixCIdx_i_2_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_2_V_read),
    .fifoCalcMatrixC_i_2_V_dout(fifoCalcMatrixC_i_2_V_dout),
    .fifoCalcMatrixC_i_2_V_empty_n(fifoCalcMatrixC_i_2_V_empty_n),
    .fifoCalcMatrixC_i_2_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_2_V_read),
    .fifoMatrixCIdx_i_1_V_dout(fifoMatrixCIdx_i_1_V_dout),
    .fifoMatrixCIdx_i_1_V_empty_n(fifoMatrixCIdx_i_1_V_empty_n),
    .fifoMatrixCIdx_i_1_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_1_V_read),
    .fifoCalcMatrixC_i_1_V_dout(fifoCalcMatrixC_i_1_V_dout),
    .fifoCalcMatrixC_i_1_V_empty_n(fifoCalcMatrixC_i_1_V_empty_n),
    .fifoCalcMatrixC_i_1_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_1_V_read),
    .fifoMatrixCIdx_i_0_V_dout(fifoMatrixCIdx_i_0_V_dout),
    .fifoMatrixCIdx_i_0_V_empty_n(fifoMatrixCIdx_i_0_V_empty_n),
    .fifoMatrixCIdx_i_0_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_0_V_read),
    .fifoCalcMatrixC_i_0_V_dout(fifoCalcMatrixC_i_0_V_dout),
    .fifoCalcMatrixC_i_0_V_empty_n(fifoCalcMatrixC_i_0_V_empty_n),
    .fifoCalcMatrixC_i_0_V_read(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_0_V_read),
    .matrixC_buffer_V_0_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_address0),
    .matrixC_buffer_V_0_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_ce0),
    .matrixC_buffer_V_0_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_we0),
    .matrixC_buffer_V_0_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_d0),
    .matrixC_buffer_V_0_q0(matrixC_buffer_V_0_q0),
    .matrixC_buffer_V_1_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_address0),
    .matrixC_buffer_V_1_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_ce0),
    .matrixC_buffer_V_1_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_we0),
    .matrixC_buffer_V_1_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_d0),
    .matrixC_buffer_V_1_q0(matrixC_buffer_V_1_q0),
    .matrixC_buffer_V_2_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_address0),
    .matrixC_buffer_V_2_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_ce0),
    .matrixC_buffer_V_2_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_we0),
    .matrixC_buffer_V_2_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_d0),
    .matrixC_buffer_V_2_q0(matrixC_buffer_V_2_q0),
    .matrixC_buffer_V_3_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_address0),
    .matrixC_buffer_V_3_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_ce0),
    .matrixC_buffer_V_3_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_we0),
    .matrixC_buffer_V_3_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_d0),
    .matrixC_buffer_V_3_q0(matrixC_buffer_V_3_q0),
    .matrixC_buffer_V_4_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_address0),
    .matrixC_buffer_V_4_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_ce0),
    .matrixC_buffer_V_4_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_we0),
    .matrixC_buffer_V_4_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_d0),
    .matrixC_buffer_V_4_q0(matrixC_buffer_V_4_q0),
    .matrixC_buffer_V_5_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_address0),
    .matrixC_buffer_V_5_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_ce0),
    .matrixC_buffer_V_5_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_we0),
    .matrixC_buffer_V_5_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_d0),
    .matrixC_buffer_V_5_q0(matrixC_buffer_V_5_q0),
    .matrixC_buffer_V_6_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_address0),
    .matrixC_buffer_V_6_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_ce0),
    .matrixC_buffer_V_6_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_we0),
    .matrixC_buffer_V_6_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_d0),
    .matrixC_buffer_V_6_q0(matrixC_buffer_V_6_q0),
    .matrixC_buffer_V_7_address0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_address0),
    .matrixC_buffer_V_7_ce0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_ce0),
    .matrixC_buffer_V_7_we0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_we0),
    .matrixC_buffer_V_7_d0(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_d0),
    .matrixC_buffer_V_7_q0(matrixC_buffer_V_7_q0)
);

sort_C_mux_83_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_83_32_1_1_U31(
    .din0(matrixC_buffer_V_0_load_reg_1209),
    .din1(matrixC_buffer_V_1_load_reg_1214),
    .din2(matrixC_buffer_V_2_load_reg_1219),
    .din3(matrixC_buffer_V_3_load_reg_1224),
    .din4(matrixC_buffer_V_4_load_reg_1229),
    .din5(matrixC_buffer_V_5_load_reg_1234),
    .din6(matrixC_buffer_V_6_load_reg_1239),
    .din7(matrixC_buffer_V_7_load_reg_1244),
    .din8(p_Val2_s_fu_692_p9),
    .dout(p_Val2_s_fu_692_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start_reg <= 1'b1;
        end else if ((grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_ready == 1'b1)) begin
            grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd1))) begin
        i_1_fu_224 <= fifoEdgeListPtr_i_V_dout;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_1_fu_224 <= tmp_47_reg_1142;
    end
end

always @ (posedge ap_clk) begin
    if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln143_fu_594_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln143_fu_594_p2 == 1'd0))) begin
        i_2_fu_228 <= 4'd0;
    end else if (((icmp_ln169_fu_676_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        i_2_fu_228 <= add_ln168_reg_1164;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_184 <= 4'd0;
    end else if (((icmp_ln136_fu_567_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_fu_184 <= add_ln135_reg_1064;
    end
end

always @ (posedge ap_clk) begin
    if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd1))) begin
        iter_fu_220 <= 31'd0;
    end else if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln143_fu_594_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln143_fu_594_p2 == 1'd1))) begin
        iter_fu_220 <= iter_2_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11))) begin
        j_1_reg_463 <= add_ln169_reg_1252;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        j_1_reg_463 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd0))) begin
        j_reg_452 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        j_reg_452 <= add_ln136_reg_1131;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln135_reg_1064 <= add_ln135_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln136_reg_1131 <= add_ln136_fu_573_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd1))) begin
        add_ln143_reg_1123 <= add_ln143_fu_552_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln168_reg_1164 <= add_ln168_fu_670_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln169_reg_1252 <= add_ln169_fu_682_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln169_fu_676_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        icmp_ln988_reg_1257 <= icmp_ln988_fu_706_p2;
        m_4_reg_1267 <= {{m_3_fu_922_p2[63:1]}};
        p_Result_2_reg_1262 <= p_Val2_s_fu_692_p10[32'd31];
        p_Result_s_reg_1272 <= m_3_fu_922_p2[32'd25];
        trunc_ln996_reg_1277 <= trunc_ln996_fu_946_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd0))) begin
        matrixC_buffer_V_0_addr_reg_1069 <= zext_ln135_fu_528_p1;
        matrixC_buffer_V_1_addr_reg_1074 <= zext_ln135_fu_528_p1;
        matrixC_buffer_V_2_addr_reg_1079 <= zext_ln135_fu_528_p1;
        matrixC_buffer_V_3_addr_reg_1084 <= zext_ln135_fu_528_p1;
        matrixC_buffer_V_4_addr_reg_1089 <= zext_ln135_fu_528_p1;
        matrixC_buffer_V_5_addr_reg_1094 <= zext_ln135_fu_528_p1;
        matrixC_buffer_V_6_addr_reg_1099 <= zext_ln135_fu_528_p1;
        matrixC_buffer_V_7_addr_reg_1104 <= zext_ln135_fu_528_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        matrixC_buffer_V_0_load_reg_1209 <= matrixC_buffer_V_0_q0;
        matrixC_buffer_V_1_load_reg_1214 <= matrixC_buffer_V_1_q0;
        matrixC_buffer_V_2_load_reg_1219 <= matrixC_buffer_V_2_q0;
        matrixC_buffer_V_3_load_reg_1224 <= matrixC_buffer_V_3_q0;
        matrixC_buffer_V_4_load_reg_1229 <= matrixC_buffer_V_4_q0;
        matrixC_buffer_V_5_load_reg_1234 <= matrixC_buffer_V_5_q0;
        matrixC_buffer_V_6_load_reg_1239 <= matrixC_buffer_V_6_q0;
        matrixC_buffer_V_7_load_reg_1244 <= matrixC_buffer_V_7_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln143_fu_594_p2 == 1'd1))) begin
        tmp_47_reg_1142 <= fifoEdgeListPtr_i_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_s_reg_1156[33 : 2] <= tmp_s_fu_636_p3[33 : 2];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0)))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln143_fu_594_p2 == 1'd1))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln168_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln168_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_0_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_0_V_read;
    end else begin
        fifoCalcMatrixC_i_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_1_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_1_V_read;
    end else begin
        fifoCalcMatrixC_i_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_2_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_2_V_read;
    end else begin
        fifoCalcMatrixC_i_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_3_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_3_V_read;
    end else begin
        fifoCalcMatrixC_i_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_4_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_4_V_read;
    end else begin
        fifoCalcMatrixC_i_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_5_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_5_V_read;
    end else begin
        fifoCalcMatrixC_i_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_6_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_6_V_read;
    end else begin
        fifoCalcMatrixC_i_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoCalcMatrixC_i_7_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoCalcMatrixC_i_7_V_read;
    end else begin
        fifoCalcMatrixC_i_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state5) & (icmp_ln143_fu_594_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd1)))) begin
        fifoEdgeListPtr_i_V_blk_n = fifoEdgeListPtr_i_V_empty_n;
    end else begin
        fifoEdgeListPtr_i_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln143_fu_594_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln143_fu_594_p2 == 1'd1)) | (~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd1)))) begin
        fifoEdgeListPtr_i_V_read = 1'b1;
    end else begin
        fifoEdgeListPtr_i_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_0_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_0_V_read;
    end else begin
        fifoMatrixCIdx_i_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_1_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_1_V_read;
    end else begin
        fifoMatrixCIdx_i_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_2_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_2_V_read;
    end else begin
        fifoMatrixCIdx_i_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_3_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_3_V_read;
    end else begin
        fifoMatrixCIdx_i_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_4_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_4_V_read;
    end else begin
        fifoMatrixCIdx_i_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_5_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_5_V_read;
    end else begin
        fifoMatrixCIdx_i_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_6_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_6_V_read;
    end else begin
        fifoMatrixCIdx_i_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        fifoMatrixCIdx_i_7_V_read = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_fifoMatrixCIdx_i_7_V_read;
    end else begin
        fifoMatrixCIdx_i_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd0))) begin
        fifoSortMatrixC_o_0_V_blk_n = fifoSortMatrixC_o_0_V_full_n;
    end else begin
        fifoSortMatrixC_o_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd0))) begin
        fifoSortMatrixC_o_0_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd1))) begin
        fifoSortMatrixC_o_1_V_blk_n = fifoSortMatrixC_o_1_V_full_n;
    end else begin
        fifoSortMatrixC_o_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd1))) begin
        fifoSortMatrixC_o_1_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd2))) begin
        fifoSortMatrixC_o_2_V_blk_n = fifoSortMatrixC_o_2_V_full_n;
    end else begin
        fifoSortMatrixC_o_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd2))) begin
        fifoSortMatrixC_o_2_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd3))) begin
        fifoSortMatrixC_o_3_V_blk_n = fifoSortMatrixC_o_3_V_full_n;
    end else begin
        fifoSortMatrixC_o_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd3))) begin
        fifoSortMatrixC_o_3_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd4))) begin
        fifoSortMatrixC_o_4_V_blk_n = fifoSortMatrixC_o_4_V_full_n;
    end else begin
        fifoSortMatrixC_o_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd4))) begin
        fifoSortMatrixC_o_4_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd5))) begin
        fifoSortMatrixC_o_5_V_blk_n = fifoSortMatrixC_o_5_V_full_n;
    end else begin
        fifoSortMatrixC_o_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd5))) begin
        fifoSortMatrixC_o_5_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd6))) begin
        fifoSortMatrixC_o_6_V_blk_n = fifoSortMatrixC_o_6_V_full_n;
    end else begin
        fifoSortMatrixC_o_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11) & (j_1_reg_463 == 4'd6))) begin
        fifoSortMatrixC_o_6_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~(j_1_reg_463 == 4'd6) & ~(j_1_reg_463 == 4'd5) & ~(j_1_reg_463 == 4'd4) & ~(j_1_reg_463 == 4'd3) & ~(j_1_reg_463 == 4'd2) & ~(j_1_reg_463 == 4'd1) & ~(j_1_reg_463 == 4'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        fifoSortMatrixC_o_7_V_blk_n = fifoSortMatrixC_o_7_V_full_n;
    end else begin
        fifoSortMatrixC_o_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (ap_predicate_op261_write_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        fifoSortMatrixC_o_7_V_write = 1'b1;
    end else begin
        fifoSortMatrixC_o_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_0_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_0_address0 = matrixC_buffer_V_0_addr_reg_1069;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_0_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_address0;
    end else begin
        matrixC_buffer_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_0_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_ce0;
    end else begin
        matrixC_buffer_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_0_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_0_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_d0;
    end else begin
        matrixC_buffer_V_0_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd0) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_0_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_0_we0;
    end else begin
        matrixC_buffer_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_1_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_1_address0 = matrixC_buffer_V_1_addr_reg_1074;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_1_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_address0;
    end else begin
        matrixC_buffer_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_1_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_ce0;
    end else begin
        matrixC_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_1_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_1_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_d0;
    end else begin
        matrixC_buffer_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd1) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_1_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_1_we0;
    end else begin
        matrixC_buffer_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_2_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_2_address0 = matrixC_buffer_V_2_addr_reg_1079;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_2_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_address0;
    end else begin
        matrixC_buffer_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_2_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_ce0;
    end else begin
        matrixC_buffer_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_2_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_2_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_d0;
    end else begin
        matrixC_buffer_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd2) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_2_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_2_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_2_we0;
    end else begin
        matrixC_buffer_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_3_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_3_address0 = matrixC_buffer_V_3_addr_reg_1084;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_3_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_address0;
    end else begin
        matrixC_buffer_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_3_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_ce0;
    end else begin
        matrixC_buffer_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_3_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_3_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_d0;
    end else begin
        matrixC_buffer_V_3_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd3) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_3_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_3_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_3_we0;
    end else begin
        matrixC_buffer_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_4_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_4_address0 = matrixC_buffer_V_4_addr_reg_1089;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_4_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_address0;
    end else begin
        matrixC_buffer_V_4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_4_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_4_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_ce0;
    end else begin
        matrixC_buffer_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_4_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_4_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_d0;
    end else begin
        matrixC_buffer_V_4_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd4) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_4_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_4_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_4_we0;
    end else begin
        matrixC_buffer_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_5_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_5_address0 = matrixC_buffer_V_5_addr_reg_1094;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_5_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_address0;
    end else begin
        matrixC_buffer_V_5_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_5_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_5_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_ce0;
    end else begin
        matrixC_buffer_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_5_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_5_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_d0;
    end else begin
        matrixC_buffer_V_5_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd5) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_5_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_5_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_5_we0;
    end else begin
        matrixC_buffer_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_6_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_6_address0 = matrixC_buffer_V_6_addr_reg_1099;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_6_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_address0;
    end else begin
        matrixC_buffer_V_6_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_6_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_6_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_ce0;
    end else begin
        matrixC_buffer_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_6_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_6_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_d0;
    end else begin
        matrixC_buffer_V_6_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd6) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_6_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_6_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_6_we0;
    end else begin
        matrixC_buffer_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        matrixC_buffer_V_7_address0 = zext_ln168_fu_652_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_7_address0 = matrixC_buffer_V_7_addr_reg_1104;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_7_address0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_address0;
    end else begin
        matrixC_buffer_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_7_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_7_ce0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_ce0;
    end else begin
        matrixC_buffer_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        matrixC_buffer_V_7_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_7_d0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_d0;
    end else begin
        matrixC_buffer_V_7_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln137_fu_579_p1 == 3'd7) & (icmp_ln136_fu_567_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        matrixC_buffer_V_7_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        matrixC_buffer_V_7_we0 = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_matrixC_buffer_V_7_we0;
    end else begin
        matrixC_buffer_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln135_fu_540_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln136_fu_567_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln143_fu_594_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln143_fu_594_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if ((~((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln143_fu_594_p2 == 1'd1)) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln143_fu_594_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln168_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln169_fu_676_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~(((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_994_p1 = p_Result_5_fu_982_p5[31:0];

assign add_ln1011_fu_864_p2 = ($signed(sub_ln997_fu_752_p2) + $signed(32'd4294967271));

assign add_ln1017_fu_969_p2 = (sub_ln1017_fu_964_p2 + select_ln996_fu_957_p3);

assign add_ln135_fu_546_p2 = (i_fu_184 + 4'd1);

assign add_ln136_fu_573_p2 = (j_reg_452 + 4'd1);

assign add_ln143_fu_552_p2 = ($signed(lenEdgeListPtr) + $signed(32'd4294967295));

assign add_ln168_fu_670_p2 = (i_2_fu_228 + 4'd1);

assign add_ln169_fu_682_p2 = (j_1_reg_463 + 4'd1);

assign and_ln1002_1_fu_880_p2 = (xor_ln1002_fu_836_p2 & p_Result_4_fu_842_p3);

assign and_ln1002_fu_812_p2 = (tmp_V_2_fu_726_p3 & or_ln1002_1_fu_806_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11 = (((ap_predicate_op261_write_state11 == 1'b1) & (fifoSortMatrixC_o_7_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd6) & (fifoSortMatrixC_o_6_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd5) & (fifoSortMatrixC_o_5_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd4) & (fifoSortMatrixC_o_4_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd3) & (fifoSortMatrixC_o_3_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd2) & (fifoSortMatrixC_o_2_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd1) & (fifoSortMatrixC_o_1_V_full_n == 1'b0)) | ((j_1_reg_463 == 4'd0) & (fifoSortMatrixC_o_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2 = ((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln135_fu_540_p2 == 1'd1));
end

always @ (*) begin
    ap_block_state5 = ((fifoEdgeListPtr_i_V_empty_n == 1'b0) & (icmp_ln143_fu_594_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op261_write_state11 = (~(j_1_reg_463 == 4'd6) & ~(j_1_reg_463 == 4'd5) & ~(j_1_reg_463 == 4'd4) & ~(j_1_reg_463 == 4'd3) & ~(j_1_reg_463 == 4'd2) & ~(j_1_reg_463 == 4'd1) & ~(j_1_reg_463 == 4'd0));
end

assign bitcast_ln751_fu_998_p1 = LD_fu_994_p1;

assign empty_24_fu_618_p2 = (($signed(i_1_fu_224) > $signed(tmp_47_reg_1142)) ? 1'b1 : 1'b0);

assign fifoSortMatrixC_o_0_V_din = select_ln988_fu_1002_p3;

assign fifoSortMatrixC_o_1_V_din = select_ln988_fu_1002_p3;

assign fifoSortMatrixC_o_2_V_din = select_ln988_fu_1002_p3;

assign fifoSortMatrixC_o_3_V_din = select_ln988_fu_1002_p3;

assign fifoSortMatrixC_o_4_V_din = select_ln988_fu_1002_p3;

assign fifoSortMatrixC_o_5_V_din = select_ln988_fu_1002_p3;

assign fifoSortMatrixC_o_6_V_din = select_ln988_fu_1002_p3;

assign fifoSortMatrixC_o_7_V_din = select_ln988_fu_1002_p3;

assign grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start = grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_475_ap_start_reg;

assign icmp_ln1002_fu_818_p2 = ((and_ln1002_fu_812_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1011_fu_850_p2 = (($signed(lsb_index_fu_758_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_540_p2 = ((i_fu_184 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_567_p2 = ((j_reg_452 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln143_fu_594_p2 = (($signed(zext_ln143_fu_590_p1) < $signed(add_ln143_reg_1123)) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_664_p2 = ((i_2_fu_228 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln169_fu_676_p2 = ((j_1_reg_463 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln988_fu_706_p2 = ((p_Val2_s_fu_692_p10 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln999_fu_774_p2 = (($signed(tmp_43_fu_764_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign iter_2_fu_599_p2 = (iter_fu_220 + 31'd1);


always @ (p_Result_3_fu_734_p4) begin
    if (p_Result_3_fu_734_p4[0] == 1'b1) begin
        l_fu_744_p3 = 32'd0;
    end else if (p_Result_3_fu_734_p4[1] == 1'b1) begin
        l_fu_744_p3 = 32'd1;
    end else if (p_Result_3_fu_734_p4[2] == 1'b1) begin
        l_fu_744_p3 = 32'd2;
    end else if (p_Result_3_fu_734_p4[3] == 1'b1) begin
        l_fu_744_p3 = 32'd3;
    end else if (p_Result_3_fu_734_p4[4] == 1'b1) begin
        l_fu_744_p3 = 32'd4;
    end else if (p_Result_3_fu_734_p4[5] == 1'b1) begin
        l_fu_744_p3 = 32'd5;
    end else if (p_Result_3_fu_734_p4[6] == 1'b1) begin
        l_fu_744_p3 = 32'd6;
    end else if (p_Result_3_fu_734_p4[7] == 1'b1) begin
        l_fu_744_p3 = 32'd7;
    end else if (p_Result_3_fu_734_p4[8] == 1'b1) begin
        l_fu_744_p3 = 32'd8;
    end else if (p_Result_3_fu_734_p4[9] == 1'b1) begin
        l_fu_744_p3 = 32'd9;
    end else if (p_Result_3_fu_734_p4[10] == 1'b1) begin
        l_fu_744_p3 = 32'd10;
    end else if (p_Result_3_fu_734_p4[11] == 1'b1) begin
        l_fu_744_p3 = 32'd11;
    end else if (p_Result_3_fu_734_p4[12] == 1'b1) begin
        l_fu_744_p3 = 32'd12;
    end else if (p_Result_3_fu_734_p4[13] == 1'b1) begin
        l_fu_744_p3 = 32'd13;
    end else if (p_Result_3_fu_734_p4[14] == 1'b1) begin
        l_fu_744_p3 = 32'd14;
    end else if (p_Result_3_fu_734_p4[15] == 1'b1) begin
        l_fu_744_p3 = 32'd15;
    end else if (p_Result_3_fu_734_p4[16] == 1'b1) begin
        l_fu_744_p3 = 32'd16;
    end else if (p_Result_3_fu_734_p4[17] == 1'b1) begin
        l_fu_744_p3 = 32'd17;
    end else if (p_Result_3_fu_734_p4[18] == 1'b1) begin
        l_fu_744_p3 = 32'd18;
    end else if (p_Result_3_fu_734_p4[19] == 1'b1) begin
        l_fu_744_p3 = 32'd19;
    end else if (p_Result_3_fu_734_p4[20] == 1'b1) begin
        l_fu_744_p3 = 32'd20;
    end else if (p_Result_3_fu_734_p4[21] == 1'b1) begin
        l_fu_744_p3 = 32'd21;
    end else if (p_Result_3_fu_734_p4[22] == 1'b1) begin
        l_fu_744_p3 = 32'd22;
    end else if (p_Result_3_fu_734_p4[23] == 1'b1) begin
        l_fu_744_p3 = 32'd23;
    end else if (p_Result_3_fu_734_p4[24] == 1'b1) begin
        l_fu_744_p3 = 32'd24;
    end else if (p_Result_3_fu_734_p4[25] == 1'b1) begin
        l_fu_744_p3 = 32'd25;
    end else if (p_Result_3_fu_734_p4[26] == 1'b1) begin
        l_fu_744_p3 = 32'd26;
    end else if (p_Result_3_fu_734_p4[27] == 1'b1) begin
        l_fu_744_p3 = 32'd27;
    end else if (p_Result_3_fu_734_p4[28] == 1'b1) begin
        l_fu_744_p3 = 32'd28;
    end else if (p_Result_3_fu_734_p4[29] == 1'b1) begin
        l_fu_744_p3 = 32'd29;
    end else if (p_Result_3_fu_734_p4[30] == 1'b1) begin
        l_fu_744_p3 = 32'd30;
    end else if (p_Result_3_fu_734_p4[31] == 1'b1) begin
        l_fu_744_p3 = 32'd31;
    end else begin
        l_fu_744_p3 = 32'd32;
    end
end

assign lsb_index_fu_758_p2 = ($signed(sub_ln997_fu_752_p2) + $signed(32'd4294967272));

assign lshr_ln1000_fu_794_p2 = 32'd4294967295 >> zext_ln1000_fu_790_p1;

assign lshr_ln1011_fu_874_p2 = zext_ln1010_fu_824_p1 >> zext_ln1011_fu_870_p1;

assign m_2_fu_910_p3 = ((icmp_ln1011_fu_850_p2[0:0] == 1'b1) ? lshr_ln1011_fu_874_p2 : shl_ln1012_fu_896_p2);

assign m_3_fu_922_p2 = (m_2_fu_910_p3 + zext_ln1014_fu_918_p1);

assign or_ln1002_1_fu_806_p2 = (shl_ln1002_fu_800_p2 | lshr_ln1000_fu_794_p2);

assign p_Result_2_fu_712_p3 = p_Val2_s_fu_692_p10[32'd31];

integer ap_tvar_int_0;

always @ (tmp_V_2_fu_726_p3) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_3_fu_734_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_3_fu_734_p4[ap_tvar_int_0] = tmp_V_2_fu_726_p3[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_4_fu_842_p3 = tmp_V_2_fu_726_p3[lsb_index_fu_758_p2];

assign p_Result_5_fu_982_p5 = {{zext_ln1015_fu_954_p1[63:32]}, {tmp_fu_975_p3}, {zext_ln1015_fu_954_p1[22:0]}};

assign p_Val2_s_fu_692_p9 = j_1_reg_463[2:0];

assign select_ln1011_fu_902_p3 = ((icmp_ln1011_fu_850_p2[0:0] == 1'b1) ? select_ln999_fu_856_p3 : and_ln1002_1_fu_880_p2);

assign select_ln988_fu_1002_p3 = ((icmp_ln988_reg_1257[0:0] == 1'b1) ? 32'd0 : bitcast_ln751_fu_998_p1);

assign select_ln996_fu_957_p3 = ((p_Result_s_reg_1272[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign select_ln999_fu_856_p3 = ((icmp_ln999_fu_774_p2[0:0] == 1'b1) ? icmp_ln1002_fu_818_p2 : p_Result_4_fu_842_p3);

assign shl_ln1002_fu_800_p2 = 32'd1 << lsb_index_fu_758_p2;

assign shl_ln1012_fu_896_p2 = zext_ln1010_fu_824_p1 << zext_ln1012_fu_892_p1;

assign smax_fu_623_p3 = ((empty_24_fu_618_p2[0:0] == 1'b1) ? i_1_fu_224 : tmp_47_reg_1142);

assign sub_ln1000_fu_784_p2 = ($signed(6'd57) - $signed(trunc_ln1000_fu_780_p1));

assign sub_ln1012_fu_886_p2 = (32'd25 - sub_ln997_fu_752_p2);

assign sub_ln1017_fu_964_p2 = (8'd16 - trunc_ln996_reg_1277);

assign sub_ln148_fu_630_p2 = (smax_fu_623_p3 - i_1_fu_224);

assign sub_ln997_fu_752_p2 = (32'd32 - l_fu_744_p3);

assign tmp_43_fu_764_p4 = {{lsb_index_fu_758_p2[31:1]}};

assign tmp_44_fu_828_p3 = lsb_index_fu_758_p2[32'd31];

assign tmp_V_2_fu_726_p3 = ((p_Result_2_fu_712_p3[0:0] == 1'b1) ? tmp_V_fu_720_p2 : p_Val2_s_fu_692_p10);

assign tmp_V_fu_720_p2 = (32'd0 - p_Val2_s_fu_692_p10);

assign tmp_fu_975_p3 = {{p_Result_2_reg_1262}, {add_ln1017_fu_969_p2}};

assign tmp_s_fu_636_p3 = {{sub_ln148_fu_630_p2}, {2'd0}};

assign trunc_ln1000_fu_780_p1 = sub_ln997_fu_752_p2[5:0];

assign trunc_ln137_fu_579_p1 = j_reg_452[2:0];

assign trunc_ln996_fu_946_p1 = l_fu_744_p3[7:0];

assign xor_ln1002_fu_836_p2 = (tmp_44_fu_828_p3 ^ 1'd1);

assign zext_ln1000_fu_790_p1 = sub_ln1000_fu_784_p2;

assign zext_ln1010_fu_824_p1 = tmp_V_2_fu_726_p3;

assign zext_ln1011_fu_870_p1 = add_ln1011_fu_864_p2;

assign zext_ln1012_fu_892_p1 = sub_ln1012_fu_886_p2;

assign zext_ln1014_fu_918_p1 = select_ln1011_fu_902_p3;

assign zext_ln1015_fu_954_p1 = m_4_reg_1267;

assign zext_ln135_fu_528_p1 = i_fu_184;

assign zext_ln143_fu_590_p1 = iter_fu_220;

assign zext_ln168_fu_652_p1 = i_2_fu_228;

always @ (posedge ap_clk) begin
    tmp_s_reg_1156[1:0] <= 2'b00;
end

endmodule //sort_C
