-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sort_C is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    lenEdgeListPtr : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoEdgeListPtr_i_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoEdgeListPtr_i_V_empty_n : IN STD_LOGIC;
    fifoEdgeListPtr_i_V_read : OUT STD_LOGIC;
    fifoMatrixCIdx_i_0_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    fifoMatrixCIdx_i_0_V_empty_n : IN STD_LOGIC;
    fifoMatrixCIdx_i_0_V_read : OUT STD_LOGIC;
    fifoMatrixCIdx_i_1_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    fifoMatrixCIdx_i_1_V_empty_n : IN STD_LOGIC;
    fifoMatrixCIdx_i_1_V_read : OUT STD_LOGIC;
    fifoCalcMatrixC_i_0_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoCalcMatrixC_i_0_V_empty_n : IN STD_LOGIC;
    fifoCalcMatrixC_i_0_V_read : OUT STD_LOGIC;
    fifoCalcMatrixC_i_1_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoCalcMatrixC_i_1_V_empty_n : IN STD_LOGIC;
    fifoCalcMatrixC_i_1_V_read : OUT STD_LOGIC;
    fifoSortMatrixC_o_0_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fifoSortMatrixC_o_0_V_full_n : IN STD_LOGIC;
    fifoSortMatrixC_o_0_V_write : OUT STD_LOGIC;
    fifoSortMatrixC_o_1_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fifoSortMatrixC_o_1_V_full_n : IN STD_LOGIC;
    fifoSortMatrixC_o_1_V_write : OUT STD_LOGIC );
end;


architecture behav of sort_C is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sort_C_sort_C,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.236333,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=693,HLS_SYN_LUT=3370,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_FFFFFFE8 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111101000";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv32_FFFFFFE7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111100111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal fifoEdgeListPtr_i_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln135_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln143_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifoSortMatrixC_o_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal icmp_ln174_reg_819 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifoSortMatrixC_o_1_V_blk_n : STD_LOGIC;
    signal add_ln135_fu_246_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln135_reg_741 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln143_fu_252_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln143_reg_760 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln136_fu_295_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_13_reg_776 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_354_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_6_reg_790 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln169_fu_376_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln169_reg_801 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln170_fu_410_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln170_reg_814 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln174_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln988_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln988_reg_823 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal p_Result_2_fu_432_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_reg_828 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_4_reg_833 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Result_s_reg_838 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln996_fu_666_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln996_reg_843 : STD_LOGIC_VECTOR (7 downto 0);
    signal matrixC_buffer_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixC_buffer_V_ce0 : STD_LOGIC;
    signal matrixC_buffer_V_we0 : STD_LOGIC;
    signal matrixC_buffer_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal matrixC_buffer_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal matrixC_buffer_V_ce1 : STD_LOGIC;
    signal matrixC_buffer_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_done : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_idle : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_ready : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_1_V_read : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_1_V_read : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_0_V_read : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_0_V_read : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce0 : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_we0 : STD_LOGIC;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce1 : STD_LOGIC;
    signal j_reg_196 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln136_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal j_1_reg_207 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln169_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10 : BOOLEAN;
    signal grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln137_fu_284_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln988_fu_399_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_130 : STD_LOGIC_VECTOR (3 downto 0);
    signal iter_fu_138 : STD_LOGIC_VECTOR (30 downto 0);
    signal iter_2_fu_317_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state4 : BOOLEAN;
    signal i_1_fu_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_fu_146 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln174_fu_714_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln137_fu_267_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_cast_fu_271_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln137_fu_279_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln143_fu_308_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_24_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal smax1_fu_341_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln148_fu_348_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln988_fu_382_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_cast_fu_386_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln988_fu_394_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_V_fu_440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_V_2_fu_446_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_3_fu_454_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_fu_464_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln997_fu_472_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lsb_index_fu_478_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_484_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln1000_fu_500_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln1000_fu_504_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln1000_fu_510_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1000_fu_514_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1002_fu_520_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1002_1_fu_526_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln1002_fu_532_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_548_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln999_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1002_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_562_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1011_fu_584_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1010_fu_544_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1011_fu_590_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln1002_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1012_fu_606_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1012_fu_612_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1011_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln999_fu_576_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1002_1_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln1011_fu_594_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln1012_fu_616_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln1011_fu_622_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_2_fu_630_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1014_fu_638_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_3_fu_642_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln1017_fu_680_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln996_fu_673_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1017_fu_685_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1015_fu_670_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_691_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_5_fu_698_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_fu_710_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sort_C_sort_C_Pipeline_loop_diff_window_loop_diff_pe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fifoMatrixCIdx_i_1_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        fifoMatrixCIdx_i_1_V_empty_n : IN STD_LOGIC;
        fifoMatrixCIdx_i_1_V_read : OUT STD_LOGIC;
        fifoCalcMatrixC_i_1_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fifoCalcMatrixC_i_1_V_empty_n : IN STD_LOGIC;
        fifoCalcMatrixC_i_1_V_read : OUT STD_LOGIC;
        zext_ln143_1 : IN STD_LOGIC_VECTOR (33 downto 0);
        fifoMatrixCIdx_i_0_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        fifoMatrixCIdx_i_0_V_empty_n : IN STD_LOGIC;
        fifoMatrixCIdx_i_0_V_read : OUT STD_LOGIC;
        fifoCalcMatrixC_i_0_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fifoCalcMatrixC_i_0_V_empty_n : IN STD_LOGIC;
        fifoCalcMatrixC_i_0_V_read : OUT STD_LOGIC;
        matrixC_buffer_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        matrixC_buffer_V_ce0 : OUT STD_LOGIC;
        matrixC_buffer_V_we0 : OUT STD_LOGIC;
        matrixC_buffer_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        matrixC_buffer_V_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        matrixC_buffer_V_ce1 : OUT STD_LOGIC;
        matrixC_buffer_V_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_C_matrixC_buffer_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    matrixC_buffer_V_U : component sort_C_matrixC_buffer_V
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => matrixC_buffer_V_address0,
        ce0 => matrixC_buffer_V_ce0,
        we0 => matrixC_buffer_V_we0,
        d0 => matrixC_buffer_V_d0,
        q0 => matrixC_buffer_V_q0,
        address1 => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_address1,
        ce1 => matrixC_buffer_V_ce1,
        q1 => matrixC_buffer_V_q1);

    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218 : component sort_C_sort_C_Pipeline_loop_diff_window_loop_diff_pe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start,
        ap_done => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_done,
        ap_idle => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_idle,
        ap_ready => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_ready,
        fifoMatrixCIdx_i_1_V_dout => fifoMatrixCIdx_i_1_V_dout,
        fifoMatrixCIdx_i_1_V_empty_n => fifoMatrixCIdx_i_1_V_empty_n,
        fifoMatrixCIdx_i_1_V_read => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_1_V_read,
        fifoCalcMatrixC_i_1_V_dout => fifoCalcMatrixC_i_1_V_dout,
        fifoCalcMatrixC_i_1_V_empty_n => fifoCalcMatrixC_i_1_V_empty_n,
        fifoCalcMatrixC_i_1_V_read => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_1_V_read,
        zext_ln143_1 => tmp_6_reg_790,
        fifoMatrixCIdx_i_0_V_dout => fifoMatrixCIdx_i_0_V_dout,
        fifoMatrixCIdx_i_0_V_empty_n => fifoMatrixCIdx_i_0_V_empty_n,
        fifoMatrixCIdx_i_0_V_read => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_0_V_read,
        fifoCalcMatrixC_i_0_V_dout => fifoCalcMatrixC_i_0_V_dout,
        fifoCalcMatrixC_i_0_V_empty_n => fifoCalcMatrixC_i_0_V_empty_n,
        fifoCalcMatrixC_i_0_V_read => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_0_V_read,
        matrixC_buffer_V_address0 => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_address0,
        matrixC_buffer_V_ce0 => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce0,
        matrixC_buffer_V_we0 => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_we0,
        matrixC_buffer_V_d0 => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_d0,
        matrixC_buffer_V_address1 => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_address1,
        matrixC_buffer_V_ce1 => grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce1,
        matrixC_buffer_V_q1 => matrixC_buffer_V_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_ready = ap_const_logic_1)) then 
                    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_1_fu_142 <= fifoEdgeListPtr_i_V_dout;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                i_1_fu_142 <= tmp_13_reg_776;
            end if; 
        end if;
    end process;

    i_2_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln143_fu_312_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_2_fu_146 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln170_fu_404_p2 = ap_const_lv1_1))) then 
                i_2_fu_146 <= add_ln169_reg_801;
            end if; 
        end if;
    end process;

    i_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_130 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln136_fu_289_p2 = ap_const_lv1_1))) then 
                i_fu_130 <= add_ln135_reg_741;
            end if; 
        end if;
    end process;

    iter_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                iter_fu_138 <= ap_const_lv31_0;
            elsif ((not(((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                iter_fu_138 <= iter_2_fu_317_p2;
            end if; 
        end if;
    end process;

    j_1_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((icmp_ln174_reg_819 = ap_const_lv1_0) and (fifoSortMatrixC_o_1_V_full_n = ap_const_logic_0)) or ((icmp_ln174_reg_819 = ap_const_lv1_1) and (fifoSortMatrixC_o_0_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                j_1_reg_207 <= add_ln170_reg_814;
            elsif (((icmp_ln169_fu_370_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                j_1_reg_207 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    j_reg_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln135_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_196 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln136_fu_289_p2 = ap_const_lv1_0))) then 
                j_reg_196 <= add_ln136_fu_295_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln135_reg_741 <= add_ln135_fu_246_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln143_reg_760 <= add_ln143_fu_252_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln169_reg_801 <= add_ln169_fu_376_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln170_reg_814 <= add_ln170_fu_410_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln170_fu_404_p2 = ap_const_lv1_0))) then
                icmp_ln174_reg_819 <= icmp_ln174_fu_416_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                icmp_ln988_reg_823 <= icmp_ln988_fu_426_p2;
                m_4_reg_833 <= m_3_fu_642_p2(63 downto 1);
                p_Result_2_reg_828 <= matrixC_buffer_V_q0(31 downto 31);
                p_Result_s_reg_838 <= m_3_fu_642_p2(25 downto 25);
                trunc_ln996_reg_843 <= trunc_ln996_fu_666_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                tmp_13_reg_776 <= fifoEdgeListPtr_i_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    tmp_6_reg_790(33 downto 2) <= tmp_6_fu_354_p3(33 downto 2);
            end if;
        end if;
    end process;
    tmp_6_reg_790(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, fifoEdgeListPtr_i_V_empty_n, fifoSortMatrixC_o_0_V_full_n, fifoSortMatrixC_o_1_V_full_n, ap_CS_fsm_state2, icmp_ln135_fu_240_p2, ap_CS_fsm_state4, icmp_ln143_fu_312_p2, ap_CS_fsm_state10, icmp_ln174_reg_819, ap_CS_fsm_state3, ap_CS_fsm_state7, ap_CS_fsm_state8, icmp_ln170_fu_404_p2, grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_done, icmp_ln136_fu_289_p2, icmp_ln169_fu_370_p2, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif ((not(((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln135_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln136_fu_289_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln143_fu_312_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif ((not(((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln169_fu_370_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln170_fu_404_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if ((not((((icmp_ln174_reg_819 = ap_const_lv1_0) and (fifoSortMatrixC_o_1_V_full_n = ap_const_logic_0)) or ((icmp_ln174_reg_819 = ap_const_lv1_1) and (fifoSortMatrixC_o_0_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    LD_fu_710_p1 <= p_Result_5_fu_698_p5(32 - 1 downto 0);
    add_ln1011_fu_584_p2 <= std_logic_vector(unsigned(sub_ln997_fu_472_p2) + unsigned(ap_const_lv32_FFFFFFE7));
    add_ln1017_fu_685_p2 <= std_logic_vector(unsigned(sub_ln1017_fu_680_p2) + unsigned(select_ln996_fu_673_p3));
    add_ln135_fu_246_p2 <= std_logic_vector(unsigned(i_fu_130) + unsigned(ap_const_lv4_1));
    add_ln136_fu_295_p2 <= std_logic_vector(unsigned(j_reg_196) + unsigned(ap_const_lv2_1));
    add_ln137_fu_279_p2 <= std_logic_vector(unsigned(tmp_4_cast_fu_271_p3) + unsigned(i_fu_130));
    add_ln143_fu_252_p2 <= std_logic_vector(unsigned(lenEdgeListPtr) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln169_fu_376_p2 <= std_logic_vector(unsigned(i_2_fu_146) + unsigned(ap_const_lv4_1));
    add_ln170_fu_410_p2 <= std_logic_vector(unsigned(j_1_reg_207) + unsigned(ap_const_lv2_1));
    add_ln988_fu_394_p2 <= std_logic_vector(unsigned(tmp_7_cast_fu_386_p3) + unsigned(i_2_fu_146));
    and_ln1002_1_fu_600_p2 <= (xor_ln1002_fu_556_p2 and p_Result_4_fu_562_p3);
    and_ln1002_fu_532_p2 <= (tmp_V_2_fu_446_p3 and or_ln1002_1_fu_526_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(fifoSortMatrixC_o_0_V_full_n, fifoSortMatrixC_o_1_V_full_n, icmp_ln174_reg_819)
    begin
        if ((((icmp_ln174_reg_819 = ap_const_lv1_0) and (fifoSortMatrixC_o_1_V_full_n = ap_const_logic_0)) or ((icmp_ln174_reg_819 = ap_const_lv1_1) and (fifoSortMatrixC_o_0_V_full_n = ap_const_logic_0)))) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(fifoEdgeListPtr_i_V_empty_n, icmp_ln135_fu_240_p2)
    begin
        if (((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(fifoEdgeListPtr_i_V_empty_n, icmp_ln143_fu_312_p2)
    begin
        if (((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_done)
    begin
        if ((grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state10_assign_proc : process(fifoSortMatrixC_o_0_V_full_n, fifoSortMatrixC_o_1_V_full_n, icmp_ln174_reg_819)
    begin
                ap_block_state10 <= (((icmp_ln174_reg_819 = ap_const_lv1_0) and (fifoSortMatrixC_o_1_V_full_n = ap_const_logic_0)) or ((icmp_ln174_reg_819 = ap_const_lv1_1) and (fifoSortMatrixC_o_0_V_full_n = ap_const_logic_0)));
    end process;


    ap_block_state2_assign_proc : process(fifoEdgeListPtr_i_V_empty_n, icmp_ln135_fu_240_p2)
    begin
                ap_block_state2 <= ((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(fifoEdgeListPtr_i_V_empty_n, icmp_ln143_fu_312_p2)
    begin
                ap_block_state4 <= ((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state7, icmp_ln169_fu_370_p2)
    begin
        if (((icmp_ln169_fu_370_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7, icmp_ln169_fu_370_p2)
    begin
        if (((icmp_ln169_fu_370_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_24_fu_336_p2 <= "1" when (signed(i_1_fu_142) > signed(tmp_13_reg_776)) else "0";

    fifoCalcMatrixC_i_0_V_read_assign_proc : process(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_0_V_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fifoCalcMatrixC_i_0_V_read <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_0_V_read;
        else 
            fifoCalcMatrixC_i_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoCalcMatrixC_i_1_V_read_assign_proc : process(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_1_V_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fifoCalcMatrixC_i_1_V_read <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoCalcMatrixC_i_1_V_read;
        else 
            fifoCalcMatrixC_i_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoEdgeListPtr_i_V_blk_n_assign_proc : process(fifoEdgeListPtr_i_V_empty_n, ap_CS_fsm_state2, icmp_ln135_fu_240_p2, ap_CS_fsm_state4, icmp_ln143_fu_312_p2)
    begin
        if ((((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            fifoEdgeListPtr_i_V_blk_n <= fifoEdgeListPtr_i_V_empty_n;
        else 
            fifoEdgeListPtr_i_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifoEdgeListPtr_i_V_read_assign_proc : process(fifoEdgeListPtr_i_V_empty_n, ap_CS_fsm_state2, icmp_ln135_fu_240_p2, ap_CS_fsm_state4, icmp_ln143_fu_312_p2)
    begin
        if (((not(((icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln143_fu_312_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (fifoEdgeListPtr_i_V_empty_n = ap_const_logic_0))) and (icmp_ln135_fu_240_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            fifoEdgeListPtr_i_V_read <= ap_const_logic_1;
        else 
            fifoEdgeListPtr_i_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoMatrixCIdx_i_0_V_read_assign_proc : process(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_0_V_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fifoMatrixCIdx_i_0_V_read <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_0_V_read;
        else 
            fifoMatrixCIdx_i_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoMatrixCIdx_i_1_V_read_assign_proc : process(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_1_V_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fifoMatrixCIdx_i_1_V_read <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_fifoMatrixCIdx_i_1_V_read;
        else 
            fifoMatrixCIdx_i_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoSortMatrixC_o_0_V_blk_n_assign_proc : process(fifoSortMatrixC_o_0_V_full_n, ap_CS_fsm_state10, icmp_ln174_reg_819)
    begin
        if (((icmp_ln174_reg_819 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            fifoSortMatrixC_o_0_V_blk_n <= fifoSortMatrixC_o_0_V_full_n;
        else 
            fifoSortMatrixC_o_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fifoSortMatrixC_o_0_V_din <= select_ln174_fu_714_p3;

    fifoSortMatrixC_o_0_V_write_assign_proc : process(fifoSortMatrixC_o_0_V_full_n, fifoSortMatrixC_o_1_V_full_n, ap_CS_fsm_state10, icmp_ln174_reg_819)
    begin
        if ((not((((icmp_ln174_reg_819 = ap_const_lv1_0) and (fifoSortMatrixC_o_1_V_full_n = ap_const_logic_0)) or ((icmp_ln174_reg_819 = ap_const_lv1_1) and (fifoSortMatrixC_o_0_V_full_n = ap_const_logic_0)))) and (icmp_ln174_reg_819 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            fifoSortMatrixC_o_0_V_write <= ap_const_logic_1;
        else 
            fifoSortMatrixC_o_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    fifoSortMatrixC_o_1_V_blk_n_assign_proc : process(fifoSortMatrixC_o_1_V_full_n, ap_CS_fsm_state10, icmp_ln174_reg_819)
    begin
        if (((icmp_ln174_reg_819 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            fifoSortMatrixC_o_1_V_blk_n <= fifoSortMatrixC_o_1_V_full_n;
        else 
            fifoSortMatrixC_o_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fifoSortMatrixC_o_1_V_din <= select_ln174_fu_714_p3;

    fifoSortMatrixC_o_1_V_write_assign_proc : process(fifoSortMatrixC_o_0_V_full_n, fifoSortMatrixC_o_1_V_full_n, ap_CS_fsm_state10, icmp_ln174_reg_819)
    begin
        if ((not((((icmp_ln174_reg_819 = ap_const_lv1_0) and (fifoSortMatrixC_o_1_V_full_n = ap_const_logic_0)) or ((icmp_ln174_reg_819 = ap_const_lv1_1) and (fifoSortMatrixC_o_0_V_full_n = ap_const_logic_0)))) and (icmp_ln174_reg_819 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            fifoSortMatrixC_o_1_V_write <= ap_const_logic_1;
        else 
            fifoSortMatrixC_o_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_ap_start_reg;
    icmp_ln1002_fu_538_p2 <= "0" when (and_ln1002_fu_532_p2 = ap_const_lv32_0) else "1";
    icmp_ln1011_fu_570_p2 <= "1" when (signed(lsb_index_fu_478_p2) > signed(ap_const_lv32_0)) else "0";
    icmp_ln135_fu_240_p2 <= "1" when (i_fu_130 = ap_const_lv4_8) else "0";
    icmp_ln136_fu_289_p2 <= "1" when (j_reg_196 = ap_const_lv2_2) else "0";
    icmp_ln143_fu_312_p2 <= "1" when (signed(zext_ln143_fu_308_p1) < signed(add_ln143_reg_760)) else "0";
    icmp_ln169_fu_370_p2 <= "1" when (i_2_fu_146 = ap_const_lv4_8) else "0";
    icmp_ln170_fu_404_p2 <= "1" when (j_1_reg_207 = ap_const_lv2_2) else "0";
    icmp_ln174_fu_416_p2 <= "1" when (j_1_reg_207 = ap_const_lv2_0) else "0";
    icmp_ln988_fu_426_p2 <= "1" when (matrixC_buffer_V_q0 = ap_const_lv32_0) else "0";
    icmp_ln999_fu_494_p2 <= "1" when (signed(tmp_fu_484_p4) > signed(ap_const_lv31_0)) else "0";
    iter_2_fu_317_p2 <= std_logic_vector(unsigned(iter_fu_138) + unsigned(ap_const_lv31_1));
    
    l_fu_464_p3_proc : process(p_Result_3_fu_454_p4)
    begin
        l_fu_464_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if p_Result_3_fu_454_p4(i) = '1' then
                l_fu_464_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    lsb_index_fu_478_p2 <= std_logic_vector(unsigned(sub_ln997_fu_472_p2) + unsigned(ap_const_lv32_FFFFFFE8));
    lshr_ln1000_fu_514_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv32_FFFFFFFF),to_integer(unsigned('0' & zext_ln1000_fu_510_p1(31-1 downto 0)))));
    lshr_ln1011_fu_594_p2 <= std_logic_vector(shift_right(unsigned(zext_ln1010_fu_544_p1),to_integer(unsigned('0' & zext_ln1011_fu_590_p1(31-1 downto 0)))));
    m_2_fu_630_p3 <= 
        lshr_ln1011_fu_594_p2 when (icmp_ln1011_fu_570_p2(0) = '1') else 
        shl_ln1012_fu_616_p2;
    m_3_fu_642_p2 <= std_logic_vector(unsigned(m_2_fu_630_p3) + unsigned(zext_ln1014_fu_638_p1));

    matrixC_buffer_V_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state8, grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_address0, ap_CS_fsm_state6, zext_ln137_fu_284_p1, zext_ln988_fu_399_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrixC_buffer_V_address0 <= zext_ln988_fu_399_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            matrixC_buffer_V_address0 <= zext_ln137_fu_284_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            matrixC_buffer_V_address0 <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_address0;
        else 
            matrixC_buffer_V_address0 <= "XXXX";
        end if; 
    end process;


    matrixC_buffer_V_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state8, grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce0, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            matrixC_buffer_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            matrixC_buffer_V_ce0 <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce0;
        else 
            matrixC_buffer_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrixC_buffer_V_ce1_assign_proc : process(grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            matrixC_buffer_V_ce1 <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_ce1;
        else 
            matrixC_buffer_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    matrixC_buffer_V_d0_assign_proc : process(ap_CS_fsm_state3, grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_d0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            matrixC_buffer_V_d0 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            matrixC_buffer_V_d0 <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_d0;
        else 
            matrixC_buffer_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    matrixC_buffer_V_we0_assign_proc : process(ap_CS_fsm_state3, grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_we0, icmp_ln136_fu_289_p2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln136_fu_289_p2 = ap_const_lv1_0))) then 
            matrixC_buffer_V_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            matrixC_buffer_V_we0 <= grp_sort_C_Pipeline_loop_diff_window_loop_diff_pe_fu_218_matrixC_buffer_V_we0;
        else 
            matrixC_buffer_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1002_1_fu_526_p2 <= (shl_ln1002_fu_520_p2 or lshr_ln1000_fu_514_p2);
    p_Result_2_fu_432_p3 <= matrixC_buffer_V_q0(31 downto 31);
    
    p_Result_3_fu_454_p4_proc : process(tmp_V_2_fu_446_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable p_Result_3_fu_454_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := tmp_V_2_fu_446_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for p_Result_3_fu_454_p4_i in 0 to 32-1 loop
                v0_cpy(p_Result_3_fu_454_p4_i) := tmp_V_2_fu_446_p3(32-1-p_Result_3_fu_454_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        p_Result_3_fu_454_p4 <= resvalue(32-1 downto 0);
    end process;

    p_Result_4_fu_562_p3 <= tmp_V_2_fu_446_p3(to_integer(unsigned(lsb_index_fu_478_p2)) downto to_integer(unsigned(lsb_index_fu_478_p2))) when (to_integer(unsigned(lsb_index_fu_478_p2))>= 0 and to_integer(unsigned(lsb_index_fu_478_p2))<=31) else "-";
    p_Result_5_fu_698_p5 <= (zext_ln1015_fu_670_p1(63 downto 32) & tmp_1_fu_691_p3 & zext_ln1015_fu_670_p1(22 downto 0));
    select_ln1011_fu_622_p3 <= 
        select_ln999_fu_576_p3 when (icmp_ln1011_fu_570_p2(0) = '1') else 
        and_ln1002_1_fu_600_p2;
    select_ln174_fu_714_p3 <= 
        ap_const_lv32_0 when (icmp_ln988_reg_823(0) = '1') else 
        LD_fu_710_p1;
    select_ln996_fu_673_p3 <= 
        ap_const_lv8_7F when (p_Result_s_reg_838(0) = '1') else 
        ap_const_lv8_7E;
    select_ln999_fu_576_p3 <= 
        icmp_ln1002_fu_538_p2 when (icmp_ln999_fu_494_p2(0) = '1') else 
        p_Result_4_fu_562_p3;
    shl_ln1002_fu_520_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & lsb_index_fu_478_p2(31-1 downto 0)))));
    shl_ln1012_fu_616_p2 <= std_logic_vector(shift_left(unsigned(zext_ln1010_fu_544_p1),to_integer(unsigned('0' & zext_ln1012_fu_612_p1(31-1 downto 0)))));
    smax1_fu_341_p3 <= 
        i_1_fu_142 when (empty_24_fu_336_p2(0) = '1') else 
        tmp_13_reg_776;
    sub_ln1000_fu_504_p2 <= std_logic_vector(signed(ap_const_lv6_39) - signed(trunc_ln1000_fu_500_p1));
    sub_ln1012_fu_606_p2 <= std_logic_vector(unsigned(ap_const_lv32_19) - unsigned(sub_ln997_fu_472_p2));
    sub_ln1017_fu_680_p2 <= std_logic_vector(unsigned(ap_const_lv8_10) - unsigned(trunc_ln996_reg_843));
    sub_ln148_fu_348_p2 <= std_logic_vector(unsigned(smax1_fu_341_p3) - unsigned(i_1_fu_142));
    sub_ln997_fu_472_p2 <= std_logic_vector(unsigned(ap_const_lv32_20) - unsigned(l_fu_464_p3));
    tmp_10_fu_548_p3 <= lsb_index_fu_478_p2(31 downto 31);
    tmp_1_fu_691_p3 <= (p_Result_2_reg_828 & add_ln1017_fu_685_p2);
    tmp_4_cast_fu_271_p3 <= (trunc_ln137_fu_267_p1 & ap_const_lv3_0);
    tmp_6_fu_354_p3 <= (sub_ln148_fu_348_p2 & ap_const_lv2_0);
    tmp_7_cast_fu_386_p3 <= (trunc_ln988_fu_382_p1 & ap_const_lv3_0);
    tmp_V_2_fu_446_p3 <= 
        tmp_V_fu_440_p2 when (p_Result_2_fu_432_p3(0) = '1') else 
        matrixC_buffer_V_q0;
    tmp_V_fu_440_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(matrixC_buffer_V_q0));
    tmp_fu_484_p4 <= lsb_index_fu_478_p2(31 downto 1);
    trunc_ln1000_fu_500_p1 <= sub_ln997_fu_472_p2(6 - 1 downto 0);
    trunc_ln137_fu_267_p1 <= j_reg_196(1 - 1 downto 0);
    trunc_ln988_fu_382_p1 <= j_1_reg_207(1 - 1 downto 0);
    trunc_ln996_fu_666_p1 <= l_fu_464_p3(8 - 1 downto 0);
    xor_ln1002_fu_556_p2 <= (tmp_10_fu_548_p3 xor ap_const_lv1_1);
    zext_ln1000_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln1000_fu_504_p2),32));
    zext_ln1010_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_2_fu_446_p3),64));
    zext_ln1011_fu_590_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1011_fu_584_p2),64));
    zext_ln1012_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln1012_fu_606_p2),64));
    zext_ln1014_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1011_fu_622_p3),64));
    zext_ln1015_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_4_reg_833),64));
    zext_ln137_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln137_fu_279_p2),64));
    zext_ln143_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iter_fu_138),32));
    zext_ln988_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln988_fu_394_p2),64));
end behav;
