-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_sparse_matrix_acc_calc_C is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    lenEdgeListPtr_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    lenEdgeListPtr_empty_n : IN STD_LOGIC;
    lenEdgeListPtr_read : OUT STD_LOGIC;
    fifoEdgeListPtr11_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoEdgeListPtr11_empty_n : IN STD_LOGIC;
    fifoEdgeListPtr11_read : OUT STD_LOGIC;
    fifoMatrixAIdx12_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoMatrixAIdx12_empty_n : IN STD_LOGIC;
    fifoMatrixAIdx12_read : OUT STD_LOGIC;
    fifoMatrixA13_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoMatrixA13_empty_n : IN STD_LOGIC;
    fifoMatrixA13_read : OUT STD_LOGIC;
    fifoMatrixB14_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fifoMatrixB14_empty_n : IN STD_LOGIC;
    fifoMatrixB14_read : OUT STD_LOGIC;
    fifoEdgeListPtr_calC15_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fifoEdgeListPtr_calC15_full_n : IN STD_LOGIC;
    fifoEdgeListPtr_calC15_write : OUT STD_LOGIC;
    fifoMatrixCIdx_o_0_0_0_0_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    fifoMatrixCIdx_o_0_0_0_0_full_n : IN STD_LOGIC;
    fifoMatrixCIdx_o_0_0_0_0_write : OUT STD_LOGIC;
    fifoMatrixCIdx_o_0_0_0_01_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    fifoMatrixCIdx_o_0_0_0_01_full_n : IN STD_LOGIC;
    fifoMatrixCIdx_o_0_0_0_01_write : OUT STD_LOGIC;
    fifoCalcMatrixC_o_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fifoCalcMatrixC_o_0_full_n : IN STD_LOGIC;
    fifoCalcMatrixC_o_0_write : OUT STD_LOGIC;
    fifoCalcMatrixC_o_02_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fifoCalcMatrixC_o_02_full_n : IN STD_LOGIC;
    fifoCalcMatrixC_o_02_write : OUT STD_LOGIC;
    lenEdgeListPtr_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    lenEdgeListPtr_c_full_n : IN STD_LOGIC;
    lenEdgeListPtr_c_write : OUT STD_LOGIC );
end;


architecture behav of krnl_sparse_matrix_acc_calc_C is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal lenEdgeListPtr_blk_n : STD_LOGIC;
    signal fifoEdgeListPtr11_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln66_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln79_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifoMatrixAIdx12_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln88_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifoMatrixA13_blk_n : STD_LOGIC;
    signal fifoMatrixB14_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln67_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_nbreadreq_fu_156_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifoEdgeListPtr_calC15_blk_n : STD_LOGIC;
    signal fifoMatrixCIdx_o_0_0_0_0_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal trunc_ln48_reg_601 : STD_LOGIC_VECTOR (0 downto 0);
    signal fifoMatrixCIdx_o_0_0_0_01_blk_n : STD_LOGIC;
    signal fifoCalcMatrixC_o_0_blk_n : STD_LOGIC;
    signal fifoCalcMatrixC_o_02_blk_n : STD_LOGIC;
    signal lenEdgeListPtr_c_blk_n : STD_LOGIC;
    signal lenEdgeListPtr_read_reg_491 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln66_fu_301_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln66_reg_502 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln79_fu_307_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln79_reg_521 : STD_LOGIC_VECTOR (31 downto 0);
    signal matrixB_buffer_addr_reg_526 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln67_fu_350_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln67_reg_534 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_predicate_op59_read_state3 : BOOLEAN;
    signal ap_block_state3 : BOOLEAN;
    signal tmp_16_fu_356_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal iter_4_fu_379_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal iter_4_reg_553 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_21_reg_558 : STD_LOGIC_VECTOR (31 downto 0);
    signal n_2_fu_404_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal n_2_reg_570 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state7 : BOOLEAN;
    signal tmp_22_fu_410_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_reg_575 : STD_LOGIC_VECTOR (31 downto 0);
    signal tempA_row_V_fu_414_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tempA_row_V_reg_580 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_19_reg_586 : STD_LOGIC_VECTOR (0 downto 0);
    signal tempA_col_V_cast_reg_591 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_16_fu_436_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln48_fu_442_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln96_fu_470_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln96_reg_613 : STD_LOGIC_VECTOR (1 downto 0);
    signal matrixB_buffer_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal matrixB_buffer_load_reg_618 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_283_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_res_reg_623 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal matrixB_buffer_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixB_buffer_ce0 : STD_LOGIC;
    signal matrixB_buffer_we0 : STD_LOGIC;
    signal j_reg_228 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal storemerge_reg_239 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_6_reg_251 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal n_reg_261 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln85_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_3_reg_272 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state13 : BOOLEAN;
    signal zext_ln69_fu_339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_fu_459_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_112 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal iter_fu_120 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_13_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_83_fu_476_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal trunc_ln69_fu_322_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_cast_fu_326_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln69_fu_334_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln79_fu_370_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_cast_fu_446_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln48_fu_454_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_condition_453 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component krnl_sparse_matrix_acc_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component krnl_sparse_matrix_acc_calc_C_matrixB_buffer IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    matrixB_buffer_U : component krnl_sparse_matrix_acc_calc_C_matrixB_buffer
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => matrixB_buffer_address0,
        ce0 => matrixB_buffer_ce0,
        we0 => matrixB_buffer_we0,
        d0 => storemerge_reg_239,
        q0 => matrixB_buffer_q0);

    fmul_32ns_32ns_32_3_max_dsp_1_U23 : component krnl_sparse_matrix_acc_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_22_reg_575,
        din1 => matrixB_buffer_load_reg_618,
        ce => ap_const_logic_1,
        dout => grp_fu_283_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_13_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1))) then 
                i_13_fu_124 <= fifoEdgeListPtr11_dout;
            elsif (((icmp_ln85_fu_385_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i_13_fu_124 <= tmp_21_reg_558;
            end if; 
        end if;
    end process;

    i_6_reg_251_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_1))) then 
                i_6_reg_251 <= i_16_fu_436_p2;
            elsif ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1))) then 
                i_6_reg_251 <= i_13_fu_124;
            end if; 
        end if;
    end process;

    i_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((lenEdgeListPtr_c_full_n = ap_const_logic_0) or (lenEdgeListPtr_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_112 <= ap_const_lv4_0;
            elsif ((not(((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln67_fu_344_p2 = ap_const_lv1_1))) then 
                i_fu_112 <= add_ln66_reg_502;
            end if; 
        end if;
    end process;

    iter_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1))) then 
                iter_fu_120 <= ap_const_lv31_0;
            elsif (((icmp_ln85_fu_385_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                iter_fu_120 <= iter_4_reg_553;
            end if; 
        end if;
    end process;

    j_3_reg_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                j_3_reg_272 <= add_ln96_reg_613;
            elsif ((not((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0))) then 
                j_3_reg_272 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    j_reg_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                j_reg_228 <= add_ln67_reg_534;
            elsif ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_0))) then 
                j_reg_228 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    n_reg_261_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln96_fu_464_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                n_reg_261 <= n_2_reg_570;
            elsif (((icmp_ln85_fu_385_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                n_reg_261 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    storemerge_reg_239_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_453)) then
                if ((tmp_nbreadreq_fu_156_p3 = ap_const_lv1_0)) then 
                    storemerge_reg_239 <= ap_const_lv32_0;
                elsif ((tmp_nbreadreq_fu_156_p3 = ap_const_lv1_1)) then 
                    storemerge_reg_239 <= tmp_16_fu_356_p1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln66_reg_502 <= add_ln66_fu_301_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                add_ln67_reg_534 <= add_ln67_fu_350_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1))) then
                add_ln79_reg_521 <= add_ln79_fu_307_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln96_reg_613 <= add_ln96_fu_470_p2;
                trunc_ln48_reg_601 <= trunc_ln48_fu_442_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                iter_4_reg_553 <= iter_4_fu_379_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                lenEdgeListPtr_read_reg_491 <= lenEdgeListPtr_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                matrixB_buffer_addr_reg_526 <= zext_ln69_fu_339_p1(4 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (tmp_19_reg_586 = ap_const_lv1_0))) then
                matrixB_buffer_load_reg_618 <= matrixB_buffer_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                n_2_reg_570 <= n_2_fu_404_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0))) then
                tempA_col_V_cast_reg_591 <= fifoMatrixAIdx12_dout(19 downto 16);
                tempA_row_V_reg_580 <= tempA_row_V_fu_414_p1;
                tmp_19_reg_586 <= fifoMatrixAIdx12_dout(15 downto 15);
                tmp_22_reg_575 <= tmp_22_fu_410_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (tmp_19_reg_586 = ap_const_lv1_0))) then
                temp_res_reg_623 <= grp_fu_283_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1))) then
                tmp_21_reg_558 <= fifoEdgeListPtr11_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, lenEdgeListPtr_empty_n, fifoEdgeListPtr11_empty_n, fifoMatrixAIdx12_empty_n, fifoMatrixA13_empty_n, fifoMatrixB14_empty_n, fifoEdgeListPtr_calC15_full_n, fifoMatrixCIdx_o_0_0_0_0_full_n, fifoMatrixCIdx_o_0_0_0_01_full_n, fifoCalcMatrixC_o_0_full_n, fifoCalcMatrixC_o_02_full_n, lenEdgeListPtr_c_full_n, ap_CS_fsm_state2, icmp_ln66_fu_295_p2, ap_CS_fsm_state5, icmp_ln79_fu_374_p2, ap_CS_fsm_state7, icmp_ln88_fu_398_p2, ap_CS_fsm_state3, icmp_ln67_fu_344_p2, ap_CS_fsm_state13, trunc_ln48_reg_601, ap_predicate_op59_read_state3, ap_CS_fsm_state8, ap_CS_fsm_state6, icmp_ln85_fu_385_p2, icmp_ln96_fu_464_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((lenEdgeListPtr_c_full_n = ap_const_logic_0) or (lenEdgeListPtr_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln67_fu_344_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln67_fu_344_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state5 => 
                if ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln85_fu_385_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif ((not((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((icmp_ln96_fu_464_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if ((not((((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln48_fu_454_p2 <= std_logic_vector(unsigned(tmp_16_cast_fu_446_p3) + unsigned(tempA_col_V_cast_reg_591));
    add_ln66_fu_301_p2 <= std_logic_vector(unsigned(i_fu_112) + unsigned(ap_const_lv4_1));
    add_ln67_fu_350_p2 <= std_logic_vector(unsigned(j_reg_228) + unsigned(ap_const_lv2_1));
    add_ln69_fu_334_p2 <= std_logic_vector(unsigned(tmp_11_cast_fu_326_p3) + unsigned(i_fu_112));
    add_ln79_fu_307_p2 <= std_logic_vector(unsigned(lenEdgeListPtr_read_reg_491) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln96_fu_470_p2 <= std_logic_vector(unsigned(j_3_reg_272) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(fifoMatrixCIdx_o_0_0_0_0_full_n, fifoMatrixCIdx_o_0_0_0_01_full_n, fifoCalcMatrixC_o_0_full_n, fifoCalcMatrixC_o_02_full_n, trunc_ln48_reg_601)
    begin
        if ((((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, lenEdgeListPtr_empty_n, lenEdgeListPtr_c_full_n)
    begin
        if (((lenEdgeListPtr_c_full_n = ap_const_logic_0) or (lenEdgeListPtr_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, icmp_ln66_fu_295_p2)
    begin
        if ((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(fifoMatrixB14_empty_n, ap_predicate_op59_read_state3)
    begin
        if (((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, icmp_ln79_fu_374_p2)
    begin
        if ((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(fifoMatrixAIdx12_empty_n, fifoMatrixA13_empty_n, icmp_ln88_fu_398_p2)
    begin
        if ((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, lenEdgeListPtr_empty_n, lenEdgeListPtr_c_full_n)
    begin
                ap_block_state1 <= ((lenEdgeListPtr_c_full_n = ap_const_logic_0) or (lenEdgeListPtr_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state13_assign_proc : process(fifoMatrixCIdx_o_0_0_0_0_full_n, fifoMatrixCIdx_o_0_0_0_01_full_n, fifoCalcMatrixC_o_0_full_n, fifoCalcMatrixC_o_02_full_n, trunc_ln48_reg_601)
    begin
                ap_block_state13 <= (((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)));
    end process;


    ap_block_state2_assign_proc : process(fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, icmp_ln66_fu_295_p2)
    begin
                ap_block_state2 <= (((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)));
    end process;


    ap_block_state3_assign_proc : process(fifoMatrixB14_empty_n, ap_predicate_op59_read_state3)
    begin
                ap_block_state3 <= ((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state5_assign_proc : process(fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, icmp_ln79_fu_374_p2)
    begin
                ap_block_state5 <= (((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)));
    end process;


    ap_block_state7_assign_proc : process(fifoMatrixAIdx12_empty_n, fifoMatrixA13_empty_n, icmp_ln88_fu_398_p2)
    begin
                ap_block_state7 <= (((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_453_assign_proc : process(fifoMatrixB14_empty_n, ap_CS_fsm_state3, icmp_ln67_fu_344_p2, ap_predicate_op59_read_state3)
    begin
                ap_condition_453 <= (not(((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln67_fu_344_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, ap_CS_fsm_state5, icmp_ln79_fu_374_p2)
    begin
        if ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op59_read_state3_assign_proc : process(icmp_ln67_fu_344_p2, tmp_nbreadreq_fu_156_p3)
    begin
                ap_predicate_op59_read_state3 <= ((tmp_nbreadreq_fu_156_p3 = ap_const_lv1_1) and (icmp_ln67_fu_344_p2 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;
    empty_83_fu_476_p3 <= 
        ap_const_lv32_0 when (tmp_19_reg_586(0) = '1') else 
        temp_res_reg_623;

    fifoCalcMatrixC_o_02_blk_n_assign_proc : process(fifoCalcMatrixC_o_02_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_1))) then 
            fifoCalcMatrixC_o_02_blk_n <= fifoCalcMatrixC_o_02_full_n;
        else 
            fifoCalcMatrixC_o_02_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fifoCalcMatrixC_o_02_din <= empty_83_fu_476_p3;

    fifoCalcMatrixC_o_02_write_assign_proc : process(fifoMatrixCIdx_o_0_0_0_0_full_n, fifoMatrixCIdx_o_0_0_0_01_full_n, fifoCalcMatrixC_o_0_full_n, fifoCalcMatrixC_o_02_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if ((not((((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_1))) then 
            fifoCalcMatrixC_o_02_write <= ap_const_logic_1;
        else 
            fifoCalcMatrixC_o_02_write <= ap_const_logic_0;
        end if; 
    end process;


    fifoCalcMatrixC_o_0_blk_n_assign_proc : process(fifoCalcMatrixC_o_0_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_0))) then 
            fifoCalcMatrixC_o_0_blk_n <= fifoCalcMatrixC_o_0_full_n;
        else 
            fifoCalcMatrixC_o_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fifoCalcMatrixC_o_0_din <= empty_83_fu_476_p3;

    fifoCalcMatrixC_o_0_write_assign_proc : process(fifoMatrixCIdx_o_0_0_0_0_full_n, fifoMatrixCIdx_o_0_0_0_01_full_n, fifoCalcMatrixC_o_0_full_n, fifoCalcMatrixC_o_02_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if ((not((((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_0))) then 
            fifoCalcMatrixC_o_0_write <= ap_const_logic_1;
        else 
            fifoCalcMatrixC_o_0_write <= ap_const_logic_0;
        end if; 
    end process;


    fifoEdgeListPtr11_blk_n_assign_proc : process(fifoEdgeListPtr11_empty_n, ap_CS_fsm_state2, icmp_ln66_fu_295_p2, ap_CS_fsm_state5, icmp_ln79_fu_374_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) then 
            fifoEdgeListPtr11_blk_n <= fifoEdgeListPtr11_empty_n;
        else 
            fifoEdgeListPtr11_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifoEdgeListPtr11_read_assign_proc : process(fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, ap_CS_fsm_state2, icmp_ln66_fu_295_p2, ap_CS_fsm_state5, icmp_ln79_fu_374_p2)
    begin
        if (((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or (not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) then 
            fifoEdgeListPtr11_read <= ap_const_logic_1;
        else 
            fifoEdgeListPtr11_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoEdgeListPtr_calC15_blk_n_assign_proc : process(fifoEdgeListPtr_calC15_full_n, ap_CS_fsm_state2, icmp_ln66_fu_295_p2, ap_CS_fsm_state5, icmp_ln79_fu_374_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) then 
            fifoEdgeListPtr_calC15_blk_n <= fifoEdgeListPtr_calC15_full_n;
        else 
            fifoEdgeListPtr_calC15_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fifoEdgeListPtr_calC15_din <= fifoEdgeListPtr11_dout;

    fifoEdgeListPtr_calC15_write_assign_proc : process(fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, ap_CS_fsm_state2, icmp_ln66_fu_295_p2, ap_CS_fsm_state5, icmp_ln79_fu_374_p2)
    begin
        if (((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or (not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln66_fu_295_p2 = ap_const_lv1_1)))) then 
            fifoEdgeListPtr_calC15_write <= ap_const_logic_1;
        else 
            fifoEdgeListPtr_calC15_write <= ap_const_logic_0;
        end if; 
    end process;


    fifoMatrixA13_blk_n_assign_proc : process(fifoMatrixA13_empty_n, ap_CS_fsm_state7, icmp_ln88_fu_398_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0))) then 
            fifoMatrixA13_blk_n <= fifoMatrixA13_empty_n;
        else 
            fifoMatrixA13_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifoMatrixA13_read_assign_proc : process(fifoMatrixAIdx12_empty_n, fifoMatrixA13_empty_n, ap_CS_fsm_state7, icmp_ln88_fu_398_p2)
    begin
        if ((not((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0))) then 
            fifoMatrixA13_read <= ap_const_logic_1;
        else 
            fifoMatrixA13_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoMatrixAIdx12_blk_n_assign_proc : process(fifoMatrixAIdx12_empty_n, ap_CS_fsm_state7, icmp_ln88_fu_398_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0))) then 
            fifoMatrixAIdx12_blk_n <= fifoMatrixAIdx12_empty_n;
        else 
            fifoMatrixAIdx12_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifoMatrixAIdx12_read_assign_proc : process(fifoMatrixAIdx12_empty_n, fifoMatrixA13_empty_n, ap_CS_fsm_state7, icmp_ln88_fu_398_p2)
    begin
        if ((not((((fifoMatrixAIdx12_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)) or ((fifoMatrixA13_empty_n = ap_const_logic_0) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln88_fu_398_p2 = ap_const_lv1_0))) then 
            fifoMatrixAIdx12_read <= ap_const_logic_1;
        else 
            fifoMatrixAIdx12_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoMatrixB14_blk_n_assign_proc : process(fifoMatrixB14_empty_n, ap_CS_fsm_state3, icmp_ln67_fu_344_p2, tmp_nbreadreq_fu_156_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_nbreadreq_fu_156_p3 = ap_const_lv1_1) and (icmp_ln67_fu_344_p2 = ap_const_lv1_0))) then 
            fifoMatrixB14_blk_n <= fifoMatrixB14_empty_n;
        else 
            fifoMatrixB14_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fifoMatrixB14_read_assign_proc : process(fifoMatrixB14_empty_n, ap_CS_fsm_state3, ap_predicate_op59_read_state3)
    begin
        if ((not(((fifoMatrixB14_empty_n = ap_const_logic_0) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_predicate_op59_read_state3 = ap_const_boolean_1))) then 
            fifoMatrixB14_read <= ap_const_logic_1;
        else 
            fifoMatrixB14_read <= ap_const_logic_0;
        end if; 
    end process;


    fifoMatrixCIdx_o_0_0_0_01_blk_n_assign_proc : process(fifoMatrixCIdx_o_0_0_0_01_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_1))) then 
            fifoMatrixCIdx_o_0_0_0_01_blk_n <= fifoMatrixCIdx_o_0_0_0_01_full_n;
        else 
            fifoMatrixCIdx_o_0_0_0_01_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fifoMatrixCIdx_o_0_0_0_01_din <= tempA_row_V_reg_580;

    fifoMatrixCIdx_o_0_0_0_01_write_assign_proc : process(fifoMatrixCIdx_o_0_0_0_0_full_n, fifoMatrixCIdx_o_0_0_0_01_full_n, fifoCalcMatrixC_o_0_full_n, fifoCalcMatrixC_o_02_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if ((not((((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_1))) then 
            fifoMatrixCIdx_o_0_0_0_01_write <= ap_const_logic_1;
        else 
            fifoMatrixCIdx_o_0_0_0_01_write <= ap_const_logic_0;
        end if; 
    end process;


    fifoMatrixCIdx_o_0_0_0_0_blk_n_assign_proc : process(fifoMatrixCIdx_o_0_0_0_0_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_0))) then 
            fifoMatrixCIdx_o_0_0_0_0_blk_n <= fifoMatrixCIdx_o_0_0_0_0_full_n;
        else 
            fifoMatrixCIdx_o_0_0_0_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fifoMatrixCIdx_o_0_0_0_0_din <= tempA_row_V_reg_580;

    fifoMatrixCIdx_o_0_0_0_0_write_assign_proc : process(fifoMatrixCIdx_o_0_0_0_0_full_n, fifoMatrixCIdx_o_0_0_0_01_full_n, fifoCalcMatrixC_o_0_full_n, fifoCalcMatrixC_o_02_full_n, ap_CS_fsm_state13, trunc_ln48_reg_601)
    begin
        if ((not((((fifoMatrixCIdx_o_0_0_0_01_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoMatrixCIdx_o_0_0_0_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)) or ((fifoCalcMatrixC_o_02_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_1)) or ((fifoCalcMatrixC_o_0_full_n = ap_const_logic_0) and (trunc_ln48_reg_601 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state13) and (trunc_ln48_reg_601 = ap_const_lv1_0))) then 
            fifoMatrixCIdx_o_0_0_0_0_write <= ap_const_logic_1;
        else 
            fifoMatrixCIdx_o_0_0_0_0_write <= ap_const_logic_0;
        end if; 
    end process;

    i_16_fu_436_p2 <= std_logic_vector(unsigned(i_6_reg_251) + unsigned(ap_const_lv32_1));
    icmp_ln66_fu_295_p2 <= "1" when (i_fu_112 = ap_const_lv4_8) else "0";
    icmp_ln67_fu_344_p2 <= "1" when (j_reg_228 = ap_const_lv2_2) else "0";
    icmp_ln79_fu_374_p2 <= "1" when (signed(zext_ln79_fu_370_p1) < signed(add_ln79_reg_521)) else "0";
    icmp_ln85_fu_385_p2 <= "1" when (signed(i_6_reg_251) < signed(tmp_21_reg_558)) else "0";
    icmp_ln88_fu_398_p2 <= "1" when (n_reg_261 = ap_const_lv2_2) else "0";
    icmp_ln96_fu_464_p2 <= "1" when (j_3_reg_272 = ap_const_lv2_2) else "0";

    internal_ap_ready_assign_proc : process(fifoEdgeListPtr11_empty_n, fifoEdgeListPtr_calC15_full_n, ap_CS_fsm_state5, icmp_ln79_fu_374_p2)
    begin
        if ((not((((fifoEdgeListPtr_calC15_full_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)) or ((fifoEdgeListPtr11_empty_n = ap_const_logic_0) and (icmp_ln79_fu_374_p2 = ap_const_lv1_1)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln79_fu_374_p2 = ap_const_lv1_0))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    iter_4_fu_379_p2 <= std_logic_vector(unsigned(iter_fu_120) + unsigned(ap_const_lv31_1));

    lenEdgeListPtr_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lenEdgeListPtr_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lenEdgeListPtr_blk_n <= lenEdgeListPtr_empty_n;
        else 
            lenEdgeListPtr_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lenEdgeListPtr_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lenEdgeListPtr_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lenEdgeListPtr_c_blk_n <= lenEdgeListPtr_c_full_n;
        else 
            lenEdgeListPtr_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lenEdgeListPtr_c_din <= lenEdgeListPtr_dout;

    lenEdgeListPtr_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lenEdgeListPtr_empty_n, lenEdgeListPtr_c_full_n)
    begin
        if ((not(((lenEdgeListPtr_c_full_n = ap_const_logic_0) or (lenEdgeListPtr_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lenEdgeListPtr_c_write <= ap_const_logic_1;
        else 
            lenEdgeListPtr_c_write <= ap_const_logic_0;
        end if; 
    end process;


    lenEdgeListPtr_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lenEdgeListPtr_empty_n, lenEdgeListPtr_c_full_n)
    begin
        if ((not(((lenEdgeListPtr_c_full_n = ap_const_logic_0) or (lenEdgeListPtr_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lenEdgeListPtr_read <= ap_const_logic_1;
        else 
            lenEdgeListPtr_read <= ap_const_logic_0;
        end if; 
    end process;


    matrixB_buffer_address0_assign_proc : process(matrixB_buffer_addr_reg_526, ap_CS_fsm_state8, ap_CS_fsm_state4, zext_ln48_fu_459_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            matrixB_buffer_address0 <= zext_ln48_fu_459_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            matrixB_buffer_address0 <= matrixB_buffer_addr_reg_526;
        else 
            matrixB_buffer_address0 <= "XXXX";
        end if; 
    end process;


    matrixB_buffer_ce0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            matrixB_buffer_ce0 <= ap_const_logic_1;
        else 
            matrixB_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    matrixB_buffer_we0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            matrixB_buffer_we0 <= ap_const_logic_1;
        else 
            matrixB_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    n_2_fu_404_p2 <= std_logic_vector(unsigned(n_reg_261) + unsigned(ap_const_lv2_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tempA_row_V_fu_414_p1 <= fifoMatrixAIdx12_dout(16 - 1 downto 0);
    tmp_11_cast_fu_326_p3 <= (trunc_ln69_fu_322_p1 & ap_const_lv3_0);
    tmp_16_cast_fu_446_p3 <= (trunc_ln48_fu_442_p1 & ap_const_lv3_0);
    tmp_16_fu_356_p1 <= fifoMatrixB14_dout;
    tmp_22_fu_410_p1 <= fifoMatrixA13_dout;
    tmp_nbreadreq_fu_156_p3 <= (0=>(fifoMatrixB14_empty_n), others=>'-');
    trunc_ln48_fu_442_p1 <= j_3_reg_272(1 - 1 downto 0);
    trunc_ln69_fu_322_p1 <= j_reg_228(1 - 1 downto 0);
    zext_ln48_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_fu_454_p2),64));
    zext_ln69_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln69_fu_334_p2),64));
    zext_ln79_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iter_fu_120),32));
end behav;
